### author by yangshichen
### 注意：脚本仅供参考，使用前请仔细阅读

In [1]:
library(ggplot2)
library(future)
library(tidyverse)
library(ggpubr)
library(ggchicklet)
library(ggsci)
library(magrittr)
library(ggh4x)
library(rstatix)
library(ggsignif)
library(ggnewscale)
library(patchwork)
library(gapminder)
library(ggprism)
library(dplyr)
library(ggplotify)
library(readr)
library(arrow)
library(ggbreak)
library(data.table)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

载入程序包：‘magrittr’


The following object is masked from ‘package:purrr’:

    set_names


The following object is masked from ‘package:tidyr’:

    extract



载入程序包：‘rstatix’


The following object is masked from ‘package:stats’:

    filter



载入程序包：‘arrow’


The following object is masked from ‘package:magrittr’:

    is_in


The following object is masked from ‘package:lubridate’:

    duration


The following object is masked from ‘package:utils’:

    timestamp


ggbreak v0.1.5 Learn more at https://yulab-smu.top/



If you use ggbreak in published research, please cite the following
paper:

S Xu, M Chen, T Feng, L Zhan, L Zhou, G Yu. Use ggbreak to effectively
utilize plotting space to deal with large datasets and outliers.
Frontiers in Genetics. 2021, 12:774846. doi: 10.3389/fgene.2021.774846



载入程序包：‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose

In [2]:
mytheme <- theme_prism(base_family="",base_fontface="plain") +
        theme(strip.text = element_text(size = 8,angle=10,vjust = 0.5,hjust = 0.5),
        axis.line = element_line(color = "black",size = 0.2),
        axis.ticks = element_line(size = 0.2),
        axis.text.y = element_text(color = "black",size = 6),
        axis.text.x = element_text(color = "black",size = 6, angle = 30,hjust = 1,vjust = 1),
        axis.title = element_text(color = "black",size = 10),
        legend.position = "none")

Warning message:
“The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.”

### eQTL-pQTL-1

In [37]:
SMR_dir <- "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/xQTL_SMR/"

# 获取所有 .smr 文件路径（包括子目录）
smr_files <- list.files(SMR_dir, pattern = "\\.smr$", recursive = TRUE, full.names = TRUE)

# 检查文件数
cat("Found", length(smr_files), "SMR result files.\n")

Found 99 SMR result files.

In [40]:
# 读取并合并
smr_list <- lapply(smr_files, function(f) {
  df <- tryCatch({
    read.table(f, header = TRUE, sep = "\t",
               stringsAsFactors = FALSE,
               colClasses = "character")
  }, error = function(e) {
    message("Error reading ", f)
    return(NULL)
  })
  
  if (!is.null(df) && nrow(df) > 0) {
    df$celltype <- tools::file_path_sans_ext(basename(f))
  }
  
  return(df)
})

In [41]:
smr_all <- bind_rows(smr_list)
smr_all$p_Outco <- as.numeric(smr_all$p_Outco)
smr_all$p_Expo <- as.numeric(smr_all$p_Expo)
smr_all$p_SMR <- as.numeric(smr_all$p_SMR)
smr_all$q_SMR <- p.adjust(smr_all$p_SMR, method = "BH")
smr_all$p_HEIDI <- as.numeric(smr_all$p_HEIDI)
smr_all

     Expo_ID Expo_Chr Expo_Gene Expo_bp   Outco_ID   Outco_Chr Outco_Gene
1    TNFRSF9 1        TNFRSF9   7915871   CAMTA1     1         CAMTA1
2    TNFRSF9 1        TNFRSF9   7915871   VAMP3      1         VAMP3
3    TNFRSF9 1        TNFRSF9   7915871   UTS2       1         UTS2
4    TNFRSF9 1        TNFRSF9   7915871   TNFRSF9    1         TNFRSF9
5    TNFRSF9 1        TNFRSF9   7915871   PARK7      1         PARK7
6    TNFRSF9 1        TNFRSF9   7915871   RERE       1         RERE
7    TNFRSF9 1        TNFRSF9   7915871   ENO1       1         ENO1
8    CD6     11       CD6       60971680  MS4A7      11        MS4A7
9    CD5     11       CD5       61102489  MS4A7      11        MS4A7
10   CD6     11       CD6       60971680  PRPF19     11        PRPF19
11   CD5     11       CD5       61102489  PRPF19     11        PRPF19
12   CD6     11       CD6       60971680  CD6        11        CD6
13   CD5     11       CD5       61102489  CD6        11        CD6
14   CD6     11       CD6       60971680  MYRF       11        MYRF
15   CD5     11       CD5       61102489  MYRF       11        MYRF
16   CD6     11       CD6       60971680  FADS2      11        FADS2
17   CD5     11       CD5       61102489  FADS2      11        FADS2
18   CD6     11       CD6       60971680  FADS1      11        FADS1
19   CD5     11       CD5       61102489  FADS1      11        FADS1
20   MMP1    11       MMP1      102789401 CEP126     11        CEP126
21   MMP1    11       MMP1      102789401 PDGFD      11        PDGFD
22   SULT1A1 16       SULT1A1   28605196  CLN3       16        CLN3
23   SULT1A1 16       SULT1A1   28605196  SGF29      16        SGF29
24   SULT1A1 16       SULT1A1   28605196  SULT1A1    16        SULT1A1
25   SULT1A1 16       SULT1A1   28605196  EIF3C      16        EIF3C
26   SULT1A1 16       SULT1A1   28605196  TUFM       16        TUFM
27   SULT1A1 16       SULT1A1   28605196  ATP2A1-AS1 16        ATP2A1-AS1
28   SULT1A1 16       SULT1A1   28605196  RABEP2     16        RABEP2
29   SULT1A1 16       SULT1A1   28605196  SPNS1      16        SPNS1
30   SULT1A1 16       SULT1A1   28605196  LAT        16        LAT
⋮    ⋮       ⋮        ⋮         ⋮         ⋮          ⋮         ⋮
6794 CCL3    17       CCL3      36088256  CCL3       17        CCL3
6795 CCL4    17       CCL4      36103827  CCL3       17        CCL3
6796 CCL23   17       CCL23     36013056  CCL4       17        CCL4
6797 CCL3    17       CCL3      36088256  CCL4       17        CCL4
6798 CCL4    17       CCL4      36103827  CCL4       17        CCL4
6799 CCL23   17       CCL23     36013056  CCL4L2     17        CCL4L2
6800 CCL3    17       CCL3      36088256  CCL4L2     17        CCL4L2
6801 CCL4    17       CCL4      36103827  CCL4L2     17        CCL4L2
6802 CCL3    17       CCL3      36088256  ACACA      17        ACACA
6803 CCL4    17       CCL4      36103827  ACACA      17        ACACA
6804 TNFSF14 19       TNFSF14   6661253   DUS3L      19        DUS3L
6805 CCL25   19       CCL25     8052318   CD320      19        CD320
6806 IL18R1  2        IL18R1    102311529 IL18RAP    2         IL18RAP
6807 CST5    20       CST5      23875934  CST3       20        CST3
6808 IL10RB  21       IL10RB    33266367  EVA1C      21        EVA1C
6809 IL10RB  21       IL10RB    33266367  TMEM50B    21        TMEM50B
6810 IL10RB  21       IL10RB    33266367  LINC00649  21        LINC00649
6811 IL10RB  21       IL10RB    33266367  MRPS6      21        MRPS6
6812 LTA     6        LTA       31572054  HLA-E      6         HLA-E
6813 LTA     6        LTA       31572054  HLA-C      6         HLA-C
6814 LTA     6        LTA       31572054  HLA-B      6         HLA-B
6815 LTA     6        LTA       31572054  MICA       6         MICA
6816 LTA     6        LTA       31572054  HCP5       6         HCP5
6817 LTA     6        LTA       31572054  MICB       6         MICB
6818 LTA     6        LTA       31572054  LTB        6         LTB
6819 LTA     6        LTA       31572054  NCR3       6         NCR3
6820 LTA     6        LTA       31572054  SNHG32     6         SNHG32
6821 LTA     6        LTA       31572054  HLA-DRB5   6         HLA-DRB5
6822 LTA     6        LTA       31572054  HLA-DRB1   6         HLA-DRB1
6823 VEGFA   6        VEGFA     43770184  PEX6       6         PEX6
     Outco_bp  topSNP           topSNP_chr ⋯ b_Expo    se_Expo   p_Expo
1    6785454   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
2    7771296   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
3    7843083   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
4    7915871   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
5    7954291   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
6    8352397   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
7    8861000   1:7931143:G:A    1          ⋯ 0.080948  0.0112921 7.579456e-13
8    60378485  11:61008737:C:T  11         ⋯ -0.214477 0.0191004 2.941038e-29
9    60378485  11:61008737:C:T  11         ⋯ 0.151929  0.0152231 1.860913e-23
10   60890547  11:61008737:C:T  11         ⋯ -0.214477 0.0191004 2.941038e-29
11   60890547  11:61008737:C:T  11         ⋯ 0.151929  0.0152231 1.860913e-23
12   60971680  11:61008737:C:T  11         ⋯ -0.214477 0.0191004 2.941038e-29
13   60971680  11:61008737:C:T  11         ⋯ 0.151929  0.0152231 1.860913e-23
14   61752636  11:61008737:C:T  11         ⋯ -0.214477 0.0191004 2.941038e-29
15   61752636  11:61008737:C:T  11         ⋯ 0.151929  0.0152231 1.860913e-23
16   61792980  11:61008737:C:T  11         ⋯ -0.214477 0.0191004 2.941038e-29
17   61792980  11:61008737:C:T  11         ⋯ 0.151929  0.0152231 1.860913e-23
18   61799627  11:61008737:C:T  11         ⋯ -0.214477 0.0191004 2.941038e-29
19   61799627  11:61008737:C:T  11         ⋯ 0.151929  0.0152231 1.860913e-23
20   101915010 11:102827000:G:A 11         ⋯ 0.237277  0.0216484 5.917324e-28
21   103907189 11:102922242:G:C 11         ⋯ -0.166583 0.025923  1.309629e-10
22   28474111  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
23   28553915  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
24   28605196  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
25   28688558  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
26   28842411  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
27   28877938  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
28   28904421  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
29   28974221  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
30   28984826  16:28608999:G:A  16         ⋯ 0.126989  0.0165622 1.755043e-14
⋮    ⋮         ⋮                ⋮          ⋱ ⋮         ⋮         ⋮
6794 36088256  17:36105010:C:A  17         ⋯ 0.172997  0.0111452 2.455842e-54
6795 36088256  17:36105010:C:A  17         ⋯ -0.183634 0.0127089 2.537605e-47
6796 36103827  17:35986879:A:G  17         ⋯ 0.461845  0.0352745 3.616483e-39
6797 36103827  17:36105010:C:A  17         ⋯ 0.172997  0.0111452 2.455842e-54
6798 36103827  17:36105010:C:A  17         ⋯ -0.183634 0.0127089 2.537605e-47
6799 36210924  17:35986879:A:G  17         ⋯ 0.461845  0.0352745 3.616483e-39
6800 36210924  17:36105010:C:A  17         ⋯ 0.172997  0.0111452 2.455842e-54
6801 36210924  17:36105010:C:A  17         ⋯ -0.183634 0.0127089 2.537605e-47
6802 37084992  17:36105010:C:A  17         ⋯ 0.172997  0.0111452 2.455842e-54
6803 37084992  17:36105010:C:A  17         ⋯ -0.183634 0.0127089 2.537605e-47
6804 5784832   19:6658052:C:T   19         ⋯ -0.126921 0.0179484 1.533646e-12
6805 8302127   19:8008072:G:T   19         ⋯ 0.178212  0.0205946 5.000246e-18
6806 102418689 2:102368964:A:G  2          ⋯ 0.369964  0.023101  1.002592e-57
6807 23626706  20:23879541:A:G  20         ⋯ 0.369955  0.0282944 4.563652e-39
6808 32412006  21:33287563:C:T  21         ⋯ 0.147571  0.0176044 5.175615e-17
6809 33432485  21:33287563:C:T  21         ⋯ 0.147571  0.0176044 5.175615e-17
6810 33915534  21:33287563:C:T  21         ⋯ 0.147571  0.0176044 5.175615e-17
6811 34073224  21:33287563:C:T  21         ⋯ 0.147571  0.0176044 5.175615e-17
6812 30489509  6:31491177:G:A   6          ⋯ -0.220074 0.0220828 2.150251e-23
6813 31268749  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6814 31353872  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6815 31399784  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6816 31463170  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6817 31494881  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6818 31580525  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6819 31588895  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6820 31834608  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6821 32517353  6:31544943:G:C   6          ⋯ -0.300376 0.0229276 3.246519e-39
6822 32577902  6:31587615:C:A   6          ⋯ -0.284345 0.0245617 5.405572e-31
6823 42963865  6:43957870:G:A   6          ⋯ -0.167079 0.0179294 1.177583e-20
     b_SMR      se_SMR   p_SMR        p_HEIDI      nsnp_HEIDI celltype
1    0.63276    0.537871 2.394293e-01 8.789142e-01 20         Adaptive NK cells
2    1.50138    0.556408 6.968435e-03 3.461237e-01 20         Adaptive NK cells
3    -10.4726   1.56857  2.447473e-11 5.282286e-02 20         Adaptive NK cells
4    7.05589    1.12663  3.780010e-10 1.439752e-01 20         Adaptive NK cells
5    0.204577   0.455708 6.534891e-01 2.074170e-08 20         Adaptive NK cells
6    -0.0311607 0.412891 9.398411e-01 4.443957e-02 20         Adaptive NK cells
7    0.531376   0.439084 2.262052e-01 8.935655e-02 20         Adaptive NK cells
8    0.224492   0.231119 3.313844e-01 3.541619e-01 17         Adaptive NK cells
9    -0.316913  0.326592 3.318650e-01 2.539811e-01 13         Adaptive NK cells
10   0.0888782  0.194073 6.469794e-01 1.924461e-01 17         Adaptive NK cells
11   -0.125468  0.274031 6.470521e-01 1.360623e-01 13         Adaptive NK cells
12   0.459648   0.234211 4.970023e-02 6.043836e-05 17         Adaptive NK cells
13   -0.648879  0.331973 5.062872e-02 5.294154e-05 13         Adaptive NK cells
14   0.272471   0.247256 2.704714e-01 1.932107e-01 17         Adaptive NK cells
15   -0.384644  0.349495 2.710842e-01 1.133668e-01 13         Adaptive NK cells
16   -0.247339  0.271195 3.617506e-01 4.005855e-01 17         Adaptive NK cells
17   0.349166   0.383179 3.621712e-01 5.083415e-01 13         Adaptive NK cells
18   -0.172213  0.262406 5.116407e-01 7.432486e-01 17         Adaptive NK cells
19   0.243112   0.370604 5.118323e-01 6.690021e-01 13         Adaptive NK cells
20   0.0350832  0.149049 8.139129e-01 9.039352e-01 20         Adaptive NK cells
21   0.0664524  0.29286  8.204952e-01 6.857948e-01 14         Adaptive NK cells
22   -0.270943  0.318744 3.953080e-01 4.223218e-03 20         Adaptive NK cells
23   -0.865007  0.347727 1.286064e-02 1.548877e-03 20         Adaptive NK cells
24   4.05286    0.654468 5.917967e-10 9.888696e-01 20         Adaptive NK cells
25   -1.23655   0.424634 3.590782e-03 1.935363e-01 20         Adaptive NK cells
26   2.21688    0.451006 8.859530e-07 8.786640e-05 20         Adaptive NK cells
27   -0.120958  0.390651 7.568401e-01 2.075479e-01 20         Adaptive NK cells
28   0.955212   0.348425 6.115762e-03 3.644501e-02 20         Adaptive NK cells
29   0.796968   0.424559 6.049530e-02 7.197801e-02 20         Adaptive NK cells
30   0.50124    0.305825 1.012184e-01 4.515913e-01 20         Adaptive NK cells
⋮    ⋮          ⋮        ⋮            ⋮            ⋮          ⋮
6794 -0.973193  0.231232 2.568171e-05 6.588012e-03 20         vNKT
6795 0.916824   0.219069 2.850490e-05 9.177104e-03 20         vNKT
6796 0.00935302 0.148349 9.497287e-01 8.329222e-01 15         vNKT
6797 1.21121    0.272706 8.936090e-06 6.970711e-02 20         vNKT
6798 -1.14105   0.258525 1.016232e-05 6.720364e-02 20         vNKT
6799 0.287105   0.142086 4.331643e-02 3.299027e-01 15         vNKT
6800 0.33352    0.250184 1.825006e-01 2.714400e-01 20         vNKT
6801 -0.314201  0.235827 1.827490e-01 2.789594e-01 20         vNKT
6802 -0.148723  0.244433 5.428966e-01 3.265355e-01 20         vNKT
6803 0.140108   0.230303 5.429443e-01 3.298146e-01 20         vNKT
6804 0.0322162  0.48466  9.470023e-01 9.208918e-01 11         vNKT
6805 0.0911283  0.257706 7.236291e-01 7.398920e-01 20         vNKT
6806 0.342951   0.117398 3.485986e-03 3.248369e-02 20         vNKT
6807 -0.0122652 0.109502 9.108161e-01 7.290550e-01 20         vNKT
6808 -0.46167   0.346135 1.822736e-01 7.143375e-01 18         vNKT
6809 0.0309338  0.329436 9.251892e-01 5.163039e-01 18         vNKT
6810 0.0212777  0.352722 9.518973e-01 7.502082e-01 18         vNKT
6811 0.182281   0.346962 5.993316e-01 8.630144e-01 18         vNKT
6812 0.218454   0.211041 3.006105e-01 1.457720e-01 20         vNKT
6813 1.05185    0.176879 2.735705e-09 4.209859e-05 20         vNKT
6814 1.6048     0.204725 4.548785e-15 4.823869e-07 20         vNKT
6815 -0.140467  0.146578 3.379070e-01 9.492512e-02 20         vNKT
6816 -0.0510719 0.1335   7.020452e-01 3.718877e-01 20         vNKT
6817 -0.451132  0.125258 3.162248e-04 2.837910e-01 20         vNKT
6818 -0.0411272 0.138538 7.665684e-01 1.824978e-01 20         vNKT
6819 -0.291596  0.154249 5.870139e-02 1.553051e-02 20         vNKT
6820 -0.0253585 0.155087 8.701159e-01 6.545750e-01 20         vNKT
6821 0.0372795  0.139077 7.886619e-01 7.233905e-02 20         vNKT
6822 0.089004   0.168662 5.977035e-01 2.216607e-02 20         vNKT
6823 -0.0934954 0.260588 7.197550e-01 1.386646e-01 12         vNKT
     q_SMR
1    6.163414e-01
2    5.219059e-02
3    8.652388e-10
4    9.277341e-09
5    8.963680e-01
6    9.848862e-01
7    5.996108e-01
8    7.024659e-01
9    7.032034e-01
10   8.930113e-01
11   8.930113e-01
12   2.494917e-01
13   2.520556e-01
14   6.503661e-01
15   6.512702e-01
16   7.270921e-01
17   7.274012e-01
18   8.311669e-01
19   8.311669e-01
20   9.486235e-01
21   9.493781e-01
22   7.556904e-01
23   8.827781e-02
24   1.402024e-08
25   2.923616e-02
26   1.386435e-05
27   9.310168e-01
28   4.651934e-02
29   2.882398e-01
30   3.981091e-01
⋮    ⋮
6794 3.291942e-04
6795 3.628525e-04
6796 9.850769e-01
6797 1.216985e-04
6798 1.370307e-04
6799 2.253238e-01
6800 5.463807e-01
6801 5.463937e-01
6802 8.441096e-01
6803 8.441096e-01
6804 9.850769e-01
6805 9.220726e-01
6806 2.855328e-02
6807 9.748807e-01
6808 5.459406e-01
6809 9.798514e-01
6810 9.850769e-01
6811 8.728366e-01
6812 6.754595e-01
6813 5.944495e-08
6814 3.042780e-13
6815 7.074507e-01
6816 9.130763e-01
6817 3.339941e-03
6818 9.348161e-01
6819 2.818576e-01
6820 9.611008e-01
6821 9.418250e-01
6822 8.719568e-01
6823 9.207806e-01

In [42]:
colnames(smr_all)

 [1] "Expo_ID"    "Expo_Chr"   "Expo_Gene"  "Expo_bp"    "Outco_ID"
 [6] "Outco_Chr"  "Outco_Gene" "Outco_bp"   "topSNP"     "topSNP_chr"
[11] "topSNP_bp"  "A1"         "A2"         "Freq"       "b_Outco"
[16] "se_Outco"   "p_Outco"    "b_Expo"     "se_Expo"    "p_Expo"
[21] "b_SMR"      "se_SMR"     "p_SMR"      "p_HEIDI"    "nsnp_HEIDI"
[26] "celltype"   "q_SMR"

In [43]:
sub_smr_all <- subset(smr_all, p_Outco < 0.00001 & p_HEIDI > 0.01 & q_SMR < 0.05 & p_Expo < 0.00000005)
sub_smr_all

     Expo_ID Expo_Chr Expo_Gene Expo_bp   Outco_ID Outco_Chr Outco_Gene
3    TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
4    TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
24   SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
82   CCL3    17       CCL3      36088256  CCL3-AS1 17        CCL3-AS1
83   CCL4    17       CCL4      36103827  CCL3-AS1 17        CCL3-AS1
88   CCL3    17       CCL3      36088256  CCL4     17        CCL4
89   CCL4    17       CCL4      36103827  CCL4     17        CCL4
137  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
226  TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
257  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
301  CCL3    17       CCL3      36088256  CCL4     17        CCL4
302  CCL4    17       CCL4      36103827  CCL4     17        CCL4
418  LTA     6        LTA       31572054  DDX39B   6         DDX39B
482  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
501  TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
520  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
542  TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
556  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
625  LTA     6        LTA       31572054  LST1     6         LST1
645  TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
646  TNFRSF9 1        TNFRSF9   7915871   PARK7    1         PARK7
662  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
714  IL18R1  2        IL18R1    102311529 IL18RAP  2         IL18RAP
777  CCL3    17       CCL3      36088256  CCL4     17        CCL4
778  CCL4    17       CCL4      36103827  CCL4     17        CCL4
781  IL18R1  2        IL18R1    102311529 IL18RAP  2         IL18RAP
814  TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
835  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
836  IL18R1  2        IL18R1    102311529 IL18RAP  2         IL18RAP
853  LTA     6        LTA       31572054  NCR3     6         NCR3
⋮    ⋮       ⋮        ⋮         ⋮         ⋮        ⋮         ⋮
5981 CXCL8   4        CXCL8     73740519  PF4V1    4         PF4V1
6057 TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
6129 TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
6156 SULT1A1 16       SULT1A1   28605196  SBK1     16        SBK1
6159 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
6160 SULT1A1 16       SULT1A1   28605196  EIF3C    16        EIF3C
6211 CCL3    17       CCL3      36088256  CCL4     17        CCL4
6212 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6268 IL18R1  2        IL18R1    102311529 IL18RAP  2         IL18RAP
6330 LTA     6        LTA       31572054  MICB     6         MICB
6332 LTA     6        LTA       31572054  NFKBIL1  6         NFKBIL1
6334 LTA     6        LTA       31572054  LST1     6         LST1
6373 TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
6390 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
6422 CCL3    17       CCL3      36088256  CCL4     17        CCL4
6423 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6437 IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
6438 IL18R1  2        IL18R1    102311529 IL18RAP  2         IL18RAP
6464 LTA     6        LTA       31572054  MICB     6         MICB
6467 LTA     6        LTA       31572054  NCR3     6         NCR3
6487 TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
6536 TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
6580 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
6602 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
6635 CCL3    17       CCL3      36088256  CCL4     17        CCL4
6636 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6742 LTA     6        LTA       31572054  DDX39B   6         DDX39B
6779 TNFRSF9 1        TNFRSF9   7915871   UTS2     1         UTS2
6797 CCL3    17       CCL3      36088256  CCL4     17        CCL4
6798 CCL4    17       CCL4      36103827  CCL4     17        CCL4
     Outco_bp  topSNP          topSNP_chr ⋯ b_Expo    se_Expo   p_Expo
3    7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
4    7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
24   28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
82   36072866  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
83   36072866  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
88   36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
89   36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
137  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
226  7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
257  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
301  36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
302  36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
418  31530219  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
482  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
501  7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
520  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
542  7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
556  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
625  31586124  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
645  7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
646  7954291   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
662  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
714  102418689 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
777  36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
778  36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
781  102418689 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
814  7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
835  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
836  102418689 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
853  31588895  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
⋮    ⋮         ⋮               ⋮          ⋱ ⋮         ⋮         ⋮
5981 73853296  4:73834715:C:T  4          ⋯ -0.120979 0.017827  1.150582e-11
6057 7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6129 7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6156 28259246  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6159 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6160 28688558  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6211 36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
6212 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6268 102418689 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
6330 31494881  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
6332 31546870  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
6334 31586124  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
6373 7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6390 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6422 36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
6423 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6437 102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
6438 102418689 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
6464 31494881  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
6467 31588895  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
6487 7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6536 7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6580 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6602 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6635 36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
6636 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6742 31530219  6:31544943:G:C  6          ⋯ -0.300376 0.0229276 3.246519e-39
6779 7843083   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6797 36103827  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
6798 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
     b_SMR     se_SMR   p_SMR        p_HEIDI    nsnp_HEIDI
3    -10.4726  1.56857  2.447473e-11 0.05282286 20
4    7.05589   1.12663  3.780010e-10 0.14397520 20
24   4.05286   0.654468 5.917967e-10 0.98886960 20
82   -1.49036  0.264405 1.733683e-08 0.02534640 20
83   1.40404   0.251607 2.401299e-08 0.03700546 20
88   1.34701   0.230743 5.292269e-09 0.20745880 20
89   -1.26899  0.219734 7.689017e-09 0.21336340 20
137  1.23784   0.123092 8.621470e-24 0.03016855 20
226  3.78913   0.708211 8.781894e-08 0.16559030 20
257  5.7094    0.835997 8.523980e-12 0.86939730 20
301  1.02627   0.221245 3.507701e-06 0.28292360 20
302  -0.966826 0.209859 4.084709e-06 0.29968130 20
418  0.811961  0.124028 5.885379e-11 0.03875023 20
482  -0.503789 0.117906 1.930339e-05 0.66223460 20
501  -7.5397   1.18962  2.328799e-10 0.08860873 20
520  -0.555382 0.12556  9.722856e-06 0.01700449 20
542  -9.38968  1.43308  5.673464e-11 0.04439689 20
556  5.63853   0.83548  1.490230e-11 0.46103640 20
625  -0.63402  0.147095 1.630445e-05 0.03694491 20
645  -9.10457  1.39848  7.498982e-11 0.03944584 20
646  -3.08136  0.65769  2.797975e-06 0.04947107 20
662  5.23371   0.786316 2.813908e-11 0.47363500 20
714  -0.855066 0.13684  4.140095e-10 0.02337096 20
777  1.75275   0.26886  7.069206e-11 0.21812300 20
778  -1.65122  0.256705 1.256214e-10 0.23374320 20
781  -0.493016 0.106242 3.475285e-06 0.53228430 20
814  -8.01663  1.26096  2.050110e-10 0.04358270 20
835  -1.68085  0.16002  8.279353e-26 0.01170593 20
836  -0.953737 0.134661 1.416003e-12 0.39590390 20
853  -0.734094 0.169085 1.414685e-05 0.37517800 20
⋮    ⋮         ⋮        ⋮            ⋮          ⋮
5981 -2.89798  0.56879  3.487710e-07 0.01922335 18
6057 -8.21335  1.28142  1.459342e-10 0.03892222 20
6129 -8.53326  1.31954  1.000774e-10 0.03107930 20
6156 -1.62628  0.393892 3.647450e-05 0.24301610 20
6159 4.47646   0.704438 2.088964e-10 0.60444550 20
6160 -1.67204  0.424625 8.227198e-05 0.14990400 20
6211 1.43484   0.225947 2.148426e-10 0.46249410 20
6212 -1.35173  0.215587 3.609888e-10 0.52435020 20
6268 -1.61925  0.152543 2.535753e-26 0.22168410 20
6330 -0.917232 0.141138 8.095102e-11 0.03253676 20
6332 0.707583  0.152487 3.479344e-06 0.34708620 20
6334 -0.737607 0.125972 4.761026e-09 0.34705970 20
6373 -9.10419  1.39539  6.822714e-11 0.02977230 20
6390 2.46477   0.519538 2.093678e-06 0.66245070 20
6422 1.3829    0.181365 2.441425e-14 0.03358212 20
6423 -1.3028   0.174007 7.043098e-14 0.03981941 20
6437 -1.3273   0.13577  1.426026e-22 0.02302868 20
6438 -1.11299  0.125201 6.133683e-19 0.04869114 20
6464 -0.681815 0.155736 1.197608e-05 0.20985350 20
6467 -0.694728 0.147259 2.384908e-06 0.08711650 20
6487 -7.46946  1.19201  3.697380e-10 0.01422633 20
6536 -7.66965  1.21312  2.577905e-10 0.03865782 20
6580 3.05162   0.623465 9.849612e-07 0.01350181 20
6602 5.6804    0.836807 1.135555e-11 0.90244360 20
6635 1.35312   0.247191 4.399931e-08 0.01338623 20
6636 -1.27475  0.235093 5.883478e-08 0.01391538 20
6742 0.945118  0.135416 2.965279e-12 0.06045084 20
6779 -7.45319  1.18533  3.218892e-10 0.04948118 20
6797 1.21121   0.272706 8.936090e-06 0.06970711 20
6798 -1.14105  0.258525 1.016232e-05 0.06720364 20
     celltype                q_SMR
3    Adaptive NK cells       8.652388e-10
4    Adaptive NK cells       9.277341e-09
24   Adaptive NK cells       1.402024e-08
82   Adaptive NK cells       3.370062e-07
83   Adaptive NK cells       4.551129e-07
88   Adaptive NK cells       1.094217e-07
89   Adaptive NK cells       1.538480e-07
137  Adaptive NK cells       2.100867e-21
226  ALPL- MARCKS- NDNs      1.556334e-06
257  ALPL- MARCKS- NDNs      3.304495e-10
301  ALPL- MARCKS- NDNs      5.049165e-05
302  ALPL- MARCKS- NDNs      5.770180e-05
418  ALPL- MARCKS- NDNs      1.921337e-09
482  Basophils               2.503936e-04
501  CCR4+ CD8+ Tcm          6.231136e-09
520  CCR4+ CD8+ Tcm          1.318868e-04
542  CD14+ cDC2              1.888295e-09
556  CD14+ cDC2              5.526000e-10
625  CD14+ cDC2              2.139332e-04
645  CD1C+ cDC2              2.336327e-09
646  CD1C+ cDC2              4.096692e-05
662  CD1C+ cDC2              9.795558e-10
714  CD1C+ cDC2              1.005262e-08
777  CD27- MAIT              2.222728e-09
778  CD27- MAIT              3.631842e-09
781  CD27- MAIT              5.018935e-05
814  CD27- Th17              5.630290e-09
835  CD27- Th17              2.824501e-23
836  CD27- Th17              6.398271e-11
853  CD27- Th17              1.874252e-04
⋮    ⋮                       ⋮
5981 RGS2- NDNs              5.665868e-06
6057 Switched Memory B cells 4.153760e-09
6129 Tfh                     2.978204e-09
6156 Tfh                     4.566340e-04
6159 Tfh                     5.692141e-09
6160 Tfh                     9.695021e-04
6211 Tfh                     5.816949e-09
6212 Tfh                     9.055245e-09
6268 Tfh                     9.611913e-24
6330 Tfh                     2.476811e-09
6332 Tfh                     5.018935e-05
6334 Tfh                     9.948537e-08
6373 Th1_Th17                2.175298e-09
6390 Th1_Th17                3.139597e-05
6422 Th1_Th17                1.411682e-12
6423 Th1_Th17                3.813893e-12
6437 Th1_Th17                3.040555e-20
6438 Th1_Th17                9.511391e-17
6464 Th1_Th17                1.605359e-04
6467 Th1_Th17                3.545148e-05
6487 Th2                     9.135147e-09
6536 Th22                    6.817460e-09
6580 VIM- FLNA- NDNs         1.527361e-05
6602 VIM- FLNA- NDNs         4.328431e-10
6635 VIM- FLNA- NDNs         8.157807e-07
6636 VIM- FLNA- NDNs         1.067632e-06
6742 VIM- FLNA- NDNs         1.264506e-10
6779 vNKT                    8.319129e-09
6797 vNKT                    1.216985e-04
6798 vNKT                    1.370307e-04

In [44]:
tmp <- subset(sub_smr_all, Expo_ID == Outco_ID)
tmp

     Expo_ID Expo_Chr Expo_Gene Expo_bp   Outco_ID Outco_Chr Outco_Gene
4    TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
24   SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
89   CCL4    17       CCL4      36103827  CCL4     17        CCL4
137  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
226  TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
257  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
302  CCL4    17       CCL4      36103827  CCL4     17        CCL4
482  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
520  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
556  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
662  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
778  CCL4    17       CCL4      36103827  CCL4     17        CCL4
835  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
900  CCL4    17       CCL4      36103827  CCL4     17        CCL4
914  IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
948  CCL4    17       CCL4      36103827  CCL4     17        CCL4
999  SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
1129 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
1145 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
1170 CCL4    17       CCL4      36103827  CCL4     17        CCL4
1229 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
1257 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
1324 CCL4    17       CCL4      36103827  CCL4     17        CCL4
1381 IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
1494 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
1527 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
1580 CCL4    17       CCL4      36103827  CCL4     17        CCL4
1635 IL10RB  21       IL10RB    33266367  IL10RB   21        IL10RB
1717 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
1756 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
⋮    ⋮       ⋮        ⋮         ⋮         ⋮        ⋮         ⋮
3978 CCL3    17       CCL3      36088256  CCL3     17        CCL3
4087 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
4121 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
4164 CCL4    17       CCL4      36103827  CCL4     17        CCL4
4371 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
4377 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
4482 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
4508 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
4528 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
4570 CCL4    17       CCL4      36103827  CCL4     17        CCL4
4761 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
4790 CCL3    17       CCL3      36088256  CCL3     17        CCL3
4932 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
4983 CCL4    17       CCL4      36103827  CCL4     17        CCL4
5209 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
5358 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
5542 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
5814 CCL3    17       CCL3      36088256  CCL3     17        CCL3
5836 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
5861 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
5895 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6159 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
6212 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6390 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
6423 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6437 IL18R1  2        IL18R1    102311529 IL18R1   2         IL18R1
6580 TNFRSF9 1        TNFRSF9   7915871   TNFRSF9  1         TNFRSF9
6602 SULT1A1 16       SULT1A1   28605196  SULT1A1  16        SULT1A1
6636 CCL4    17       CCL4      36103827  CCL4     17        CCL4
6798 CCL4    17       CCL4      36103827  CCL4     17        CCL4
     Outco_bp  topSNP          topSNP_chr ⋯ b_Expo    se_Expo   p_Expo
4    7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
24   28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
89   36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
137  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
226  7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
257  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
302  36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
482  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
520  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
556  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
662  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
778  36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
835  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
900  36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
914  102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
948  36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
999  28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
1129 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
1145 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
1170 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
1229 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
1257 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
1324 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
1381 102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
1494 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
1527 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
1580 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
1635 33266367  21:33287563:C:T 21         ⋯ 0.147571  0.0176044 5.175615e-17
1717 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
1756 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
⋮    ⋮         ⋮               ⋮          ⋱ ⋮         ⋮         ⋮
3978 36088256  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
4087 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
4121 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
4164 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
4371 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
4377 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
4482 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
4508 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
4528 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
4570 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
4761 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
4790 36088256  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
4932 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
4983 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
5209 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
5358 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
5542 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
5814 36088256  17:36105010:C:A 17         ⋯ 0.172997  0.0111452 2.455842e-54
5836 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
5861 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
5895 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6159 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6212 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6390 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6423 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6437 102311529 2:102368964:A:G 2          ⋯ 0.369964  0.023101  1.002592e-57
6580 7915871   1:7931143:G:A   1          ⋯ 0.080948  0.0112921 7.579456e-13
6602 28605196  16:28608999:G:A 16         ⋯ 0.126989  0.0165622 1.755043e-14
6636 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
6798 36103827  17:36105010:C:A 17         ⋯ -0.183634 0.0127089 2.537605e-47
     b_SMR     se_SMR   p_SMR        p_HEIDI    nsnp_HEIDI
4    7.05589   1.12663  3.780010e-10 0.14397520 20
24   4.05286   0.654468 5.917967e-10 0.98886960 20
89   -1.26899  0.219734 7.689017e-09 0.21336340 20
137  1.23784   0.123092 8.621470e-24 0.03016855 20
226  3.78913   0.708211 8.781894e-08 0.16559030 20
257  5.7094    0.835997 8.523980e-12 0.86939730 20
302  -0.966826 0.209859 4.084709e-06 0.29968130 20
482  -0.503789 0.117906 1.930339e-05 0.66223460 20
520  -0.555382 0.12556  9.722856e-06 0.01700449 20
556  5.63853   0.83548  1.490230e-11 0.46103640 20
662  5.23371   0.786316 2.813908e-11 0.47363500 20
778  -1.65122  0.256705 1.256214e-10 0.23374320 20
835  -1.68085  0.16002  8.279353e-26 0.01170593 20
900  -2.82173  0.290767 2.886245e-22 0.03921467 20
914  -0.648874 0.127167 3.351386e-07 0.01774139 20
948  -1.50458  0.24255  5.533054e-10 0.71322710 20
999  3.28542   0.579281 1.415046e-08 0.18303540 20
1129 4.06809   0.795374 3.142605e-07 0.14714540 20
1145 2.63843   0.538852 9.760920e-07 0.91192520 20
1170 -1.27334  0.191254 2.778641e-11 0.02329153 20
1229 7.1541    1.13994  3.477083e-10 0.19224080 20
1257 4.59237   0.710484 1.021607e-10 0.95804290 20
1324 -1.66233  0.218475 2.767177e-14 0.16436740 20
1381 1.60593   0.133516 2.534182e-33 0.04971967 20
1494 6.92361   1.09192  2.286008e-10 0.55086770 20
1527 2.68634   0.512114 1.557788e-07 0.41802230 20
1580 -1.68258  0.218914 1.517534e-14 0.01705207 20
1635 -1.15517  0.278371 3.328262e-05 0.24309120 18
1717 5.25576   0.88765  3.200396e-09 0.12528690 20
1756 6.14066   0.890959 5.493946e-12 0.66100820 20
⋮    ⋮         ⋮        ⋮            ⋮          ⋮
3978 1.06121   0.172842 8.263950e-10 0.14194390 20
4087 3.12376   0.602096 2.123947e-07 0.01651484 20
4121 5.53845   0.807237 6.838162e-12 0.82790740 20
4164 -1.18031  0.203601 6.744689e-09 0.01838800 20
4371 4.34831   0.763203 1.216077e-08 0.40797010 20
4377 3.04925   0.559511 5.041357e-08 0.44463660 20
4482 1.8874    0.431978 1.246950e-05 0.91659040 20
4508 2.8869    0.592869 1.119505e-06 0.01051728 20
4528 5.87128   0.851668 5.430149e-12 0.85703630 20
4570 -1.12833  0.216757 1.934534e-07 0.01247235 20
4761 2.13713   0.422134 4.134143e-07 0.48849350 20
4790 2.34994   0.25046  6.442783e-21 0.01315675 20
4932 4.35181   0.699179 4.841052e-10 0.17608390 20
4983 -0.875876 0.187673 3.055853e-06 0.22690900 20
5209 2.65973   0.498988 9.807640e-08 0.44737030 20
5358 5.3828    0.816126 4.236884e-11 0.29525010 20
5542 1.82091   0.437583 3.164638e-05 0.29063530 20
5814 -1.39231  0.274533 3.945594e-07 0.02761415 20
5836 4.05551   0.738984 4.066362e-08 0.02585820 20
5861 5.92351   0.865255 7.595615e-12 0.86878980 20
5895 -0.895787 0.18719  1.706074e-06 0.12576610 20
6159 4.47646   0.704438 2.088964e-10 0.60444550 20
6212 -1.35173  0.215587 3.609888e-10 0.52435020 20
6390 2.46477   0.519538 2.093678e-06 0.66245070 20
6423 -1.3028   0.174007 7.043098e-14 0.03981941 20
6437 -1.3273   0.13577  1.426026e-22 0.02302868 20
6580 3.05162   0.623465 9.849612e-07 0.01350181 20
6602 5.6804    0.836807 1.135555e-11 0.90244360 20
6636 -1.27475  0.235093 5.883478e-08 0.01391538 20
6798 -1.14105  0.258525 1.016232e-05 0.06720364 20
     celltype                    q_SMR
4    Adaptive NK cells           9.277341e-09
24   Adaptive NK cells           1.402024e-08
89   Adaptive NK cells           1.538480e-07
137  Adaptive NK cells           2.100867e-21
226  ALPL- MARCKS- NDNs          1.556334e-06
257  ALPL- MARCKS- NDNs          3.304495e-10
302  ALPL- MARCKS- NDNs          5.770180e-05
482  Basophils                   2.503936e-04
520  CCR4+ CD8+ Tcm              1.318868e-04
556  CD14+ cDC2                  5.526000e-10
662  CD1C+ cDC2                  9.795558e-10
778  CD27- MAIT                  3.631842e-09
835  CD27- Th17                  2.824501e-23
900  CD27+ MAIT                  5.967530e-20
914  CD27+ MAIT                  5.457400e-06
948  CD27+ Th1                   1.320001e-08
999  CD27+ Th17                  2.766435e-07
1129 CD56bright NK cells         5.129664e-06
1145 CD56bright NK cells         1.520520e-05
1170 CD56bright NK cells         9.722394e-10
1229 CD56dim NK cells            8.852290e-09
1257 CD56dim NK cells            3.017500e-09
1324 CD56dim NK cells            1.586592e-12
1381 CD56dim NK cells            1.571884e-30
1494 CD8+ Temra                  6.140721e-09
1527 CD8+ Temra                  2.663857e-06
1580 CD8+ Temra                  9.162951e-13
1635 CD8+ Temra                  4.205321e-04
1717 Core classical monocytes    6.866762e-08
1756 Core classical monocytes    2.205011e-10
⋮    ⋮                           ⋮
3978 Intermediate monocytes      1.904896e-08
4087 IRF1- GBP2- NDNs            3.595953e-06
4121 IRF1- GBP2- NDNs            2.696924e-10
4164 IRF1- GBP2- NDNs            1.357493e-07
4371 Memory CD4+ Treg            2.398062e-07
4377 Memory CD4+ Treg            9.172581e-07
4482 MMP9+ CD177+ iLDNs          1.668223e-04
4508 MT-ATP6- MT-CO2- NDNs       1.728141e-05
4528 MT-ATP6- MT-CO2- NDNs       2.192302e-10
4570 MT-ATP6- MT-CO2- NDNs       3.283414e-06
4761 Naïve B cells               6.621422e-06
4790 Naïve B cells               1.221086e-18
4932 Naïve CD4+ T cells          1.158965e-08
4983 Naïve CD4+ T cells          4.464686e-05
5209 Naïve CD8+ T cells          1.729135e-06
5358 Non-classical monocytes     1.445413e-09
5542 Non-switched memory B cells 4.013443e-04
5814 Proliferative NK cells      6.349242e-06
5836 RGS2- NDNs                  7.580543e-07
5861 RGS2- NDNs                  2.978441e-10
5895 RGS2- NDNs                  2.569656e-05
6159 Tfh                         5.692141e-09
6212 Tfh                         9.055245e-09
6390 Th1_Th17                    3.139597e-05
6423 Th1_Th17                    3.813893e-12
6437 Th1_Th17                    3.040555e-20
6580 VIM- FLNA- NDNs             1.527361e-05
6602 VIM- FLNA- NDNs             4.328431e-10
6636 VIM- FLNA- NDNs             1.067632e-06
6798 vNKT                        1.370307e-04

In [45]:
write.csv(sub_smr_all,'/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/SMR_eQTL_pQTL_1.csv')
write.csv(tmp,'/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/SMR_eQTL_pQTL_1_same.csv')

### eQTL-GWAS

In [3]:
SMR_dir <- "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR/"
disease_dirs <- list.dirs(SMR_dir, full.names = TRUE, recursive = FALSE)
all_smr_list <- list()

In [4]:
disease_dirs

  [1] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//110"
  [2] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//110.1"
  [3] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//110.11"
  [4] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//110.12"
  [5] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//110.13"
  [6] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//274"
  [7] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//274.1"
  [8] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//274.11"
  [9] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//371"
 [10] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//371.3"
 [11] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//380.1"
 [12] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//381"
 [13] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//381.1"
 [14] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//381.11"
 [15] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//411.1"
 [16] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//411.2"
 [17] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//411.3"
 [18] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//426"
 [19] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427"
 [20] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427.1"
 [21] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427.12"
 [22] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427.2"
 [23] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427.21"
 [24] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427.3"
 [25] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//427.5"
 [26] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//465"
 [27] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//483"
 [28] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//495"
 [29] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//496.21"
 [30] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//512.8"
 [31] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//522.1"
 [32] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//523"
 [33] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//530.1"
 [34] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//530.11"
 [35] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//562"
 [36] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//580"
 [37] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//585.1"
 [38] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//585.3"
 [39] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//585.33"
 [40] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//585.34"
 [41] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//585.4"
 [42] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//591"
 [43] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//593"
 [44] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//681"
 [45] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//681.1"
 [46] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//681.5"
 [47] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//681.6"
 [48] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//686.1"
 [49] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//696"
 [50] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//696.4"
 [51] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//696.41"
 [52] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//710"
 [53] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//710.1"
 [54] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//714.1"
 [55] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//727.1"
 [56] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//728.7"
 [57] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//740.1"
 [58] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//783"
 [59] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//994.2"
 [60] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Acute_glomerulonephritis"
 [61] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Acute_hepatitis_A_infection"
 [62] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Acute_pancreatitis"
 [63] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Acute_renal_failure"
 [64] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//AD"
 [65] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//AG"
 [66] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//AIH"
 [67] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Allergic_conjunctivitis"
 [68] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Allergic_rhinitis"
 [69] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Alzheimers_disease"
 [70] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Ankylosing_spondylitis"
 [71] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ApA"
 [72] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//AR"
 [73] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//As"
 [74] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Aspergillosis"
 [75] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Asthma"
 [76] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Atopic_dermatitis"
 [77] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Autoimmune_hepatitis"
 [78] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Bacterial_meningitis"
 [79] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Bacterial_pneumoniae"
 [80] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//BD"
 [81] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Behcets_disease"
 [82] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Biliary_tract_cancer"
 [83] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Br"
 [84] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Breast_cancer"
 [85] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Bronchiectasis"
 [86] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Bronchitis"
 [87] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Cataract"
 [88] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//CB"
 [89] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//CD"
 [90] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Cerebral_aneurysm"
 [91] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//CG"
 [92] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//CHB"
 [93] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//CHC"
 [94] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ChG"
 [95] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Cholecystitis"
 [96] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_bronchitis"
 [97] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_gastritis"
 [98] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_glomerulonephritis"
 [99] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_hepatitis_B"
[100] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_hepatitis_C"
[101] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_obstructive_pulmonary_disease"
[102] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_pancreatitis"
[103] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_sinusitis"
[104] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Chronic_suppurative_otitis_media"
[105] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ChS"
[106] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Cirrhosis"
[107] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Colorectal_cancer"
[108] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Congestive_heart_failure"
[109] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Contact_dermatitis"
[110] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//COPD"
[111] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Coronary_artery_disease"
[112] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Coronary_atherosclerosis"
[113] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//CRF"
[114] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Crohn_disease"
[115] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Cystitis"
[116] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Diabetic_nephropathy"
[117] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Diagnoses"
[118] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Diphtheria"
[119] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//DN"
[120] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Dysentery"
[121] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Epilepsy"
[122] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Esophageal_cancer"
[123] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//FA"
[124] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//FS"
[125] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Gastric_cancer"
[126] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Gastric_ulcer"
[127] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//GD"
[128] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Goi"
[129] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Gout"
[130] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Graves_disease"
[131] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//HAV"
[132] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//HD"
[133] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Hematological_malignancy"
[134] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Hepatic_cancer"
[135] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Hepatocellular_carcinoma"
[136] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Herpes_infection"
[137] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//HIV"
[138] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Hype"
[139] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Hypo"
[140] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Idiopathic_thrombocytopenic_purpura"
[141] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//IgA_nephropathy"
[142] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ILD"
[143] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//IN"
[144] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Inflammatory_bowel_disease"
[145] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Influenza"
[146] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Interstitial_lung_disease"
[147] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Ischemic_stroke"
[148] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ITP"
[149] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//JRA"
[150] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Lung_cancer"
[151] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//MA"
[152] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//MG"
[153] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ML"
[154] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Multiple_Sclerosis"
[155] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Myocardial_infarction"
[156] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Myocarditis"
[157] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Nephrotic_syndrome"
[158] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Non_tuberculous_mycobacterial_infection"
[159] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Nonalcoholic_fatty_liver_disease"
[160] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//NS"
[161] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Obesity"
[162] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//PA"
[163] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pancreatic_cancer"
[164] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Parkinsons_disease"
[165] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Periodontal_disease"
[166] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Peripheral_artery_disease"
[167] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//PF"
[168] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pl"
[169] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pleurisy"
[170] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//PM"
[171] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pn"
[172] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pneumonia"
[173] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pneumothorax"
[174] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pol"
[175] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pollinosis"
[176] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Polymyositis"
[177] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Psoriasis"
[178] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//PsV"
[179] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//PT"
[180] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pulmonary_tuberculosis"
[181] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pyelonephritis"
[182] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Pyoderma"
[183] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//RA"
[184] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Rheumatoid_arthritis"
[185] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Sepsis"
[186] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Severe_COVID-19_infection"
[187] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Sjgrens_syndrome"
[188] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Sjogren_syndrome"
[189] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//SLE"
[190] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//SS"
[191] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Systemic_lupus_erythematosus"
[192] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Systemic_sclerosis"
[193] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//T1D"
[194] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//T2D"
[195] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//ThC"
[196] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Ton"
[197] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Tonsillitis"
[198] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//TS"
[199] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Tuberculosis"
[200] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Type_1_diabetes"
[201] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Type_2_diabetes"
[202] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Typhoid_fever"
[203] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//UC"
[204] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Ulcerative_colitis"
[205] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Uric_acid"
[206] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Urt"
[207] "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_GWAS_SMR//Vasculitis"

In [5]:
# 遍历每个疾病文件夹
for (disease_path in disease_dirs) {
  disease_name <- basename(disease_path)  # 疾病名
  # 找出该疾病下所有smr文件
  smr_files <- list.files(disease_path, pattern = "\\.smr$", full.names = TRUE)
  if (length(smr_files) == 0) next
  # 读取每个smr文件
  for (f in smr_files) {
    # 提取细胞类型名（假设文件名类似 CD4_Tcells.smr 或 Mono.smr）
    celltype <- str_remove(basename(f), "\\.smr$")
    # 读取smr文件
    smr_df <- tryCatch({
      read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE, colClasses = "character")
    }, error = function(e) {
      message("Failed to read ", f)
      return(NULL)
    })
    # 跳过空文件
    if (is.null(smr_df) || nrow(smr_df) == 0) next
    # 添加疾病和细胞类型信息
    smr_df$disease <- disease_name
    smr_df$celltype <- celltype
    # 存入列表
    all_smr_list[[length(all_smr_list) + 1]] <- smr_df
  }
}

In [6]:
all_smr <- rbindlist(all_smr_list, fill = TRUE)
all_smr

         probeID     ProbeChr Gene        Probe_bp  topSNP          topSNP_chr
1        LINC00115   1        LINC00115   824228    1:913469:G:C    1
2        LINC01128   1        LINC01128   825138    1:913469:G:C    1
3        HES4        1        HES4        998962    1:1000453:C:G   1
4        ISG15       1        ISG15       1001138   1:1015903:C:T   1
5        TNFRSF18    1        TNFRSF18    1203508   1:1217733:G:A   1
6        TNFRSF4     1        TNFRSF4     1211326   1:1217251:C:A   1
7        SDF4        1        SDF4        1216931   1:1231507:T:C   1
8        B3GALT6     1        B3GALT6     1232237   1:1235869:T:C   1
9        CPTP        1        CPTP        1324756   1:1363031:C:T   1
10       MRPL20-AS1  1        MRPL20-AS1  1399515   1:1399922:C:T   1
11       SSU72       1        SSU72       1541673   1:1575421:C:T   1
12       MMP23B      1        MMP23B      1632163   1:1627057:C:G   1
13       SLC35E2B    1        SLC35E2B    1659529   1:1674848:G:C   1
14       CDK11A      1        CDK11A      1702379   1:1683909:A:C   1
15       PRKCZ       1        PRKCZ       2050411   1:2050397:C:T   1
16       PLCH2       1        PLCH2       2425980   1:2423124:C:T   1
17       TNFRSF14    1        TNFRSF14    2555639   1:2551482:T:C   1
18       WRAP73      1        WRAP73      3630767   1:3609076:G:A   1
19       C1orf174    1        C1orf174    3889125   1:3884683:T:G   1
20       KCNAB2      1        KCNAB2      5990927   1:6019318:A:G   1
21       VAMP3       1        VAMP3       7771296   1:7910323:T:C   1
22       UTS2        1        UTS2        7843083   1:7910032:C:T   1
23       TNFRSF9     1        TNFRSF9     7915871   1:7910032:C:T   1
24       PARK7       1        PARK7       7954291   1:7910323:T:C   1
25       RERE        1        RERE        8352397   1:8371547:C:T   1
26       H6PD        1        H6PD        9234774   1:9235735:G:C   1
27       SPSB1       1        SPSB1       9292894   1:9289365:A:G   1
28       CENPS       1        CENPS       10430433  1:10431152:G:A  1
29       FBXO2       1        FBXO2       11637018  1:11654736:A:G  1
30       FBXO6       1        FBXO6       11664200  1:11665661:G:A  1
⋮        ⋮           ⋮        ⋮           ⋮         ⋮               ⋮
14579188 TRBV28      7        TRBV28      142720660 7:142714038:C:T 7
14579189 TRBC1       7        TRBC1       142791694 7:142783765:G:C 7
14579190 MYOM2       8        MYOM2       2045046   8:2137125:C:T   8
14579191 CSGALNACT1  8        CSGALNACT1  19404161  8:19459759:A:G  8
14579192 IKBKB       8        IKBKB       42271302  8:42319645:G:A  8
14579193 MSC         8        MSC         71841560  8:71863643:T:A  8
14579194 TERF1       8        TERF1       73008856  8:73183186:G:A  8
14579195 TPD52       8        TPD52       80034745  8:80138778:C:T  8
14579196 PAG1        8        PAG1        80967810  8:81135593:C:A  8
14579197 CPQ         8        CPQ         96645242  8:96643078:C:G  8
14579198 MTSS1       8        MTSS1       124550784 8:124565893:A:T 8
14579199 LRATD2      8        LRATD2      126552443 8:126504433:C:T 8
14579200 LY6E        8        LY6E        143017982 8:143004333:G:A 8
14579201 CPSF1       8        CPSF1       144393229 8:144399250:C:T 8
14579202 RPL8        8        RPL8        144789765 8:144783791:T:C 8
14579203 TTC39B      9        TTC39B      15163622  9:15301430:C:A  9
14579204 B4GALT1     9        B4GALT1     33104082  9:33122628:T:C  9
14579205 NUDT2       9        NUDT2       34329506  9:34346284:C:T  9
14579206 GRHPR       9        GRHPR       37422666  9:37422659:C:T  9
14579207 NMRK1       9        NMRK1       75060573  9:75090654:T:C  9
14579208 GNAQ        9        GNAQ        77716097  9:78044904:C:G  9
14579209 SEMA4D      9        SEMA4D      89360787  9:89480480:C:T  9
14579210 SYK         9        SYK         90801787  9:90809055:G:A  9
14579211 ERCC6L2-AS1 9        ERCC6L2-AS1 95759231  9:95787982:C:T  9
14579212 LINC01505   9        LINC01505   105993310 9:106243413:A:C 9
14579213 STOM        9        STOM        121338987 9:121338684:G:C 9
14579214 RPL12       9        RPL12       127447674 9:127467373:A:G 9
14579215 DNLZ        9        DNLZ        136359480 9:136366042:T:G 9
14579216 NOTCH1      9        NOTCH1      136494433 9:136618317:C:T 9
14579217 PTGDS       9        PTGDS       136975092 9:136937244:C:T 9
         topSNP_bp A1 A2 Freq     ⋯ b_eQTL    se_eQTL   p_eQTL
1        913469    C  G  0.102594 ⋯ 0.754036  0.078988  1.345376e-21
2        913469    C  G  0.102594 ⋯ 0.965222  0.0741122 8.960174e-39
3        1000453   C  G  0.126179 ⋯ 0.580657  0.0654351 7.069643e-19
4        1015903   C  T  0.231132 ⋯ 0.190143  0.0308707 7.304699e-10
5        1217733   A  G  0.268278 ⋯ -0.721839 0.0438161 5.615836e-61
6        1217251   A  C  0.266509 ⋯ -0.653871 0.0426808 5.620573e-53
7        1231507   C  T  0.23467  ⋯ -0.327702 0.0398609 2.015586e-16
8        1235869   C  T  0.224646 ⋯ -0.359584 0.0399259 2.131788e-19
9        1363031   C  T  0.17158  ⋯ 0.810526  0.0464073 2.624344e-68
10       1399922   T  C  0.113208 ⋯ -0.561624 0.0538927 1.985297e-25
11       1575421   C  T  0.139741 ⋯ -0.479681 0.0560479 1.144301e-17
12       1627057   G  C  0.321344 ⋯ -0.28955  0.0412854 2.326344e-12
13       1674848   G  C  0.336085 ⋯ 0.446271  0.0399321 5.359654e-29
14       1683909   A  C  0.489387 ⋯ 0.411434  0.0447026 3.454450e-20
15       2050397   C  T  0.326061 ⋯ -0.47118  0.0415283 7.762298e-30
16       2423124   T  C  0.134434 ⋯ 0.691389  0.0568604 5.112411e-34
17       2551482   C  T  0.492925 ⋯ 0.383492  0.0356053 4.737499e-27
18       3609076   A  G  0.412736 ⋯ 0.241755  0.038824  4.755966e-10
19       3884683   T  G  0.438679 ⋯ -0.285246 0.0398881 8.604477e-13
20       6019318   G  A  0.285967 ⋯ -0.284186 0.0418256 1.086572e-11
21       7910323   T  C  0.393868 ⋯ 0.233272  0.0406797 9.788583e-09
22       7910032   C  T  0.420401 ⋯ -1.06008  0.0415618 1.680920e-143
23       7910032   C  T  0.420401 ⋯ 0.691254  0.0424421 1.221014e-59
24       7910323   T  C  0.393868 ⋯ 0.352526  0.0349914 7.151710e-24
25       8371547   T  C  0.150354 ⋯ -0.251674 0.0461125 4.820288e-08
26       9235735   G  C  0.462264 ⋯ 0.584754  0.0348038 2.382928e-63
27       9289365   G  A  0.129127 ⋯ 0.790043  0.0575069 5.993407e-43
28       10431152  A  G  0.161557 ⋯ 0.347571  0.0577348 1.742743e-09
29       11654736  A  G  0.180425 ⋯ 0.785481  0.0527227 3.378515e-50
30       11665661  A  G  0.414505 ⋯ -0.322673 0.0303268 1.943719e-26
⋮        ⋮         ⋮  ⋮  ⋮        ⋱ ⋮         ⋮         ⋮
14579188 142714038 T  C  0.31191  ⋯ -0.370472 0.0485598 2.362493e-14
14579189 142783765 C  G  0.136792 ⋯ 0.602029  0.0648751 1.697805e-20
14579190 2137125   T  C  0.426297 ⋯ 0.823219  0.0424984 1.366318e-83
14579191 19459759  A  G  0.165094 ⋯ 0.365693  0.0547438 2.387965e-11
14579192 42319645  A  G  0.123231 ⋯ -0.391728 0.0647619 1.459897e-09
14579193 71863643  A  T  0.367335 ⋯ 0.234589  0.0417314 1.894149e-08
14579194 73183186  A  G  0.318396 ⋯ -0.294546 0.0460066 1.531037e-10
14579195 80138778  C  T  0.216981 ⋯ -0.309242 0.0452854 8.565688e-12
14579196 81135593  A  C  0.195165 ⋯ 0.304777  0.0540033 1.664593e-08
14579197 96643078  C  G  0.394458 ⋯ -0.355832 0.0413055 7.015316e-18
14579198 124565893 A  T  0.446344 ⋯ 0.271806  0.0406715 2.341619e-11
14579199 126504433 T  C  0.300118 ⋯ -0.310046 0.0449132 5.083226e-12
14579200 143004333 A  G  0.342571 ⋯ -0.362011 0.0449149 7.633904e-16
14579201 144399250 C  T  0.345519 ⋯ 0.360517  0.0423946 1.834418e-17
14579202 144783791 C  T  0.282429 ⋯ -0.412022 0.05018   2.195632e-16
14579203 15301430  A  C  0.288915 ⋯ -0.298866 0.0459686 7.950977e-11
14579204 33122628  T  C  0.418042 ⋯ -0.344263 0.0435472 2.668564e-15
14579205 34346284  T  C  0.477594 ⋯ 0.29167   0.0432741 1.583325e-11
14579206 37422659  T  C  0.435731 ⋯ 0.346749  0.0401858 6.207924e-18
14579207 75090654  C  T  0.481722 ⋯ -0.375048 0.0439548 1.431278e-17
14579208 78044904  G  C  0.189269 ⋯ 0.358653  0.0493389 3.616941e-13
14579209 89480480  T  C  0.397406 ⋯ -0.243988 0.0443564 3.784322e-08
14579210 90809055  A  G  0.434552 ⋯ -0.314104 0.0411395 2.256748e-14
14579211 95787982  T  C  0.370283 ⋯ -0.334448 0.0424914 3.519444e-15
14579212 106243413 C  A  0.495873 ⋯ 0.231216  0.0413136 2.186086e-08
14579213 121338684 C  G  0.145047 ⋯ -0.341443 0.0577796 3.433411e-09
14579214 127467373 G  A  0.418042 ⋯ 0.352567  0.044511  2.358140e-15
14579215 136366042 G  T  0.105542 ⋯ 0.692577  0.064488  6.631660e-27
14579216 136618317 T  C  0.417453 ⋯ -0.326878 0.0431994 3.827258e-14
14579217 136937244 C  T  0.169222 ⋯ -0.285045 0.0480156 2.911596e-09
         b_SMR       se_SMR    p_SMR        p_HEIDI      nsnp_HEIDI disease
1        -0.0425695  0.0303973 1.613834e-01 9.389883e-01 20         110
2        -0.0332554  0.023628  1.592911e-01 9.789697e-01 20         110
3        0.0451232   0.0331989 1.740902e-01 6.294022e-01 20         110
4        0.096067    0.0774727 2.149712e-01 7.739581e-01 20         110
5        0.0248688   0.0203157 2.209064e-01 2.585718e-01 20         110
6        0.0299354   0.0224409 1.822141e-01 2.946277e-01 20         110
7        0.0829247   0.0513187 1.061209e-01 4.074960e-01 20         110
8        0.0918693   0.0473614 5.241006e-02 6.053866e-01 20         110
9        0.0122949   0.0201205 5.411574e-01 3.976492e-01 20         110
10       0.00818553  0.0387693 8.327825e-01 3.287489e-01 20         110
11       -0.00340874 0.0418393 9.350663e-01 5.847773e-01 20         110
12       0.0722743   0.048417  1.355036e-01 8.695838e-01 20         110
13       0.0012939   0.0328594 9.685899e-01 2.173184e-01 20         110
14       0.0250329   0.0310625 4.203074e-01 9.294175e-01 20         110
15       0.0364173   0.0291833 2.120756e-01 7.236741e-01 20         110
16       0.0354139   0.0267271 1.851651e-01 6.765151e-02 11         110
17       0.0232874   0.0330033 4.804315e-01 7.042600e-02 20         110
18       -0.111646   0.0593521 5.996090e-02 1.113517e-02 20         110
19       -0.0380222  0.045163  3.998504e-01 6.106763e-01 11         110
20       0.0264535   0.0487377 5.872862e-01 6.170077e-01 20         110
21       -0.0141799  0.0569702 8.034377e-01 1.885380e-01 11         110
22       0.00295001  0.0123125 8.106442e-01 2.361582e-02 20         110
23       -0.00452404 0.0188832 8.106561e-01 3.479136e-02 20         110
24       -0.00938306 0.037674  8.033150e-01 2.279350e-01 20         110
25       0.0493409   0.0714963 4.901198e-01 8.544940e-02 18         110
26       -0.0243373  0.0216953 2.619580e-01 7.883065e-01 20         110
27       0.00351906  0.0236916 8.819196e-01 5.969007e-01 11         110
28       -0.124262   0.0596614 3.727016e-02 8.730311e-02 20         110
29       -0.00420405 0.0204574 8.371798e-01 1.863463e-01 20         110
30       0.0362717   0.0401026 3.657453e-01 5.064212e-01 16         110
⋮        ⋮           ⋮         ⋮            ⋮            ⋮          ⋮
14579188 0.053928    0.0433893 2.139086e-01 7.929531e-01 20         Urt
14579189 -0.0255753  0.0337096 4.480347e-01 8.262403e-01 15         Urt
14579190 0.00406825  0.0182984 8.240586e-01 7.966780e-01 20         Urt
14579191 0.00744642  0.0543906 8.911048e-01 7.076883e-01 20         Urt
14579192 -0.00123484 0.05981   9.835280e-01 4.487816e-01 5          Urt
14579193 -0.0277889  0.0686696 6.857164e-01 8.633179e-01 12         Urt
14579194 0.0872741   0.0602965 1.477803e-01 3.165271e-01 14         Urt
14579195 -0.0238455  0.0569679 6.755249e-01 8.198043e-01 20         Urt
14579196 -0.022549   0.0654786 7.305668e-01 9.543589e-01 8          Urt
14579197 0.099909    0.0456499 2.862649e-02 1.258296e-01 19         Urt
14579198 -0.0175958  0.0555141 7.512730e-01 1.688651e-01 20         Urt
14579199 -0.0554297  0.0544932 3.090655e-01 2.898318e-01 19         Urt
14579200 0.0635442   0.0493281 1.976788e-01 2.550672e-01 20         Urt
14579201 0.00165021  0.043578  9.697930e-01 7.168911e-01 20         Urt
14579202 -0.0177919  0.0411257 6.652884e-01 2.189931e-01 20         Urt
14579203 0.0256731   0.0522493 6.231734e-01 8.296421e-01 20         Urt
14579204 0.0504639   0.0440266 2.517060e-01 4.697829e-01 20         Urt
14579205 0.0520296   0.0528655 3.250233e-01 3.643944e-02 20         Urt
14579206 0.0613133   0.0457486 1.801728e-01 7.792302e-01 9          Urt
14579207 0.0308331   0.0399555 4.402997e-01 1.574214e-01 20         Urt
14579208 0.000641793 0.0573455 9.910705e-01 9.570390e-01 20         Urt
14579209 0.0687914   0.0690551 3.191620e-01 6.811876e-02 19         Urt
14579210 -0.0789148  0.0486981 1.051270e-01 5.913822e-01 20         Urt
14579211 0.0322471   0.0466604 4.895009e-01 7.688126e-01 20         Urt
14579212 -0.0285106  0.0658509 6.650464e-01 9.507186e-01 20         Urt
14579213 -0.0409143  0.0604943 4.988291e-01 7.390771e-01 14         Urt
14579214 -0.0491162  0.0441978 2.664469e-01 8.361037e-01 20         Urt
14579215 0.0129229   0.0394186 7.430338e-01 6.691955e-01 20         Urt
14579216 0.0405234   0.0465506 3.840148e-01 5.232031e-01 8          Urt
14579217 -0.0735801  0.0719012 3.061420e-01 6.025068e-01 14         Urt
         celltype
1        eQTLsmr_Adaptive NK cells
2        eQTLsmr_Adaptive NK cells
3        eQTLsmr_Adaptive NK cells
4        eQTLsmr_Adaptive NK cells
5        eQTLsmr_Adaptive NK cells
6        eQTLsmr_Adaptive NK cells
7        eQTLsmr_Adaptive NK cells
8        eQTLsmr_Adaptive NK cells
9        eQTLsmr_Adaptive NK cells
10       eQTLsmr_Adaptive NK cells
11       eQTLsmr_Adaptive NK cells
12       eQTLsmr_Adaptive NK cells
13       eQTLsmr_Adaptive NK cells
14       eQTLsmr_Adaptive NK cells
15       eQTLsmr_Adaptive NK cells
16       eQTLsmr_Adaptive NK cells
17       eQTLsmr_Adaptive NK cells
18       eQTLsmr_Adaptive NK cells
19       eQTLsmr_Adaptive NK cells
20       eQTLsmr_Adaptive NK cells
21       eQTLsmr_Adaptive NK cells
22       eQTLsmr_Adaptive NK cells
23       eQTLsmr_Adaptive NK cells
24       eQTLsmr_Adaptive NK cells
25       eQTLsmr_Adaptive NK cells
26       eQTLsmr_Adaptive NK cells
27       eQTLsmr_Adaptive NK cells
28       eQTLsmr_Adaptive NK cells
29       eQTLsmr_Adaptive NK cells
30       eQTLsmr_Adaptive NK cells
⋮        ⋮
14579188 eQTLsmr_vNKT
14579189 eQTLsmr_vNKT
14579190 eQTLsmr_vNKT
14579191 eQTLsmr_vNKT
14579192 eQTLsmr_vNKT
14579193 eQTLsmr_vNKT
14579194 eQTLsmr_vNKT
14579195 eQTLsmr_vNKT
14579196 eQTLsmr_vNKT
14579197 eQTLsmr_vNKT
14579198 eQTLsmr_vNKT
14579199 eQTLsmr_vNKT
14579200 eQTLsmr_vNKT
14579201 eQTLsmr_vNKT
14579202 eQTLsmr_vNKT
14579203 eQTLsmr_vNKT
14579204 eQTLsmr_vNKT
14579205 eQTLsmr_vNKT
14579206 eQTLsmr_vNKT
14579207 eQTLsmr_vNKT
14579208 eQTLsmr_vNKT
14579209 eQTLsmr_vNKT
14579210 eQTLsmr_vNKT
14579211 eQTLsmr_vNKT
14579212 eQTLsmr_vNKT
14579213 eQTLsmr_vNKT
14579214 eQTLsmr_vNKT
14579215 eQTLsmr_vNKT
14579216 eQTLsmr_vNKT
14579217 eQTLsmr_vNKT

In [7]:
colnames(all_smr)

 [1] "probeID"    "ProbeChr"   "Gene"       "Probe_bp"   "topSNP"
 [6] "topSNP_chr" "topSNP_bp"  "A1"         "A2"         "Freq"
[11] "b_GWAS"     "se_GWAS"    "p_GWAS"     "b_eQTL"     "se_eQTL"
[16] "p_eQTL"     "b_SMR"      "se_SMR"     "p_SMR"      "p_HEIDI"
[21] "nsnp_HEIDI" "disease"    "celltype"

In [8]:
all_smr$p_GWAS <- as.numeric(all_smr$p_GWAS)
all_smr$p_eQTL <- as.numeric(all_smr$p_eQTL)
all_smr$p_SMR <- as.numeric(all_smr$p_SMR)
all_smr <- all_smr %>% group_by(disease) %>% mutate(q_SMR = p.adjust(p_SMR, method = "BH")) %>% ungroup()
all_smr$p_HEIDI <- as.numeric(all_smr$p_HEIDI)

In [9]:
min(all_smr$q_SMR)

[1] 6.463894e-63

In [10]:
sub_smr_all <- subset(all_smr, p_GWAS < 0.00001 & p_HEIDI > 0.01 & q_SMR < 0.05 & p_eQTL < 0.00000005)
sub_smr_all

     probeID  ProbeChr Gene     Probe_bp topSNP          topSNP_chr topSNP_bp
1    WDR1     4        WDR1     10068089 4:10113515:G:A  4          10113515
2    ABCG2    4        ABCG2    88090150 4:88143450:C:T  4          88143450
3    WDR1     4        WDR1     10068089 4:10105174:C:T  4          10105174
4    WDR1     4        WDR1     10068089 4:10072546:A:T  4          10072546
5    ABCG2    4        ABCG2    88090150 4:88205495:C:T  4          88205495
6    WDR1     4        WDR1     10068089 4:10113515:G:A  4          10113515
7    ABCG2    4        ABCG2    88090150 4:88143450:C:T  4          88143450
8    WDR1     4        WDR1     10068089 4:10105174:C:T  4          10105174
9    WDR1     4        WDR1     10068089 4:10072546:A:T  4          10072546
10   ABCG2    4        ABCG2    88090150 4:88205495:C:T  4          88205495
11   WDR1     4        WDR1     10068089 4:10243716:T:C  4          10243716
12   WDR1     4        WDR1     10068089 4:10113515:G:A  4          10113515
13   CASP9    1        CASP9    15490832 1:15554742:T:G  1          15554742
14   CASP9    1        CASP9    15490832 1:15528387:T:G  1          15528387
15   ABCG2    4        ABCG2    88090150 4:88143450:C:T  4          88143450
16   WDR1     4        WDR1     10068089 4:10105174:C:T  4          10105174
17   WDR1     4        WDR1     10068089 4:10072546:A:T  4          10072546
18   ABCG2    4        ABCG2    88090150 4:88205495:C:T  4          88205495
19   CDKN1C   11       CDKN1C   2883213  11:2837406:C:T  11         2837406
20   BAZ1A    14       BAZ1A    34752731 14:34967136:C:G 14         34967136
21   SRP54    14       SRP54    34981957 14:34929051:T:C 14         34929051
22   PPP2R3C  14       PPP2R3C  35085467 14:35119090:A:C 14         35119090
23   PRORP    14       PRORP    35121846 14:35150610:A:G 14         35150610
24   SGSH     17       SGSH     80206716 17:80202780:T:C 17         80202780
25   SLC26A11 17       SLC26A11 80219699 17:80220775:C:A 17         80220775
26   UBE2L3   22       UBE2L3   21549447 22:21563468:G:A 22         21563468
27   HLA-F    6        HLA-F    29722775 6:29728468:T:C  6          29728468
28   SRP54    14       SRP54    34981957 14:34993700:T:A 14         34993700
29   PPP2R3C  14       PPP2R3C  35085467 14:35124900:C:G 14         35124900
30   PRORP    14       PRORP    35121846 14:35135686:A:C 14         35135686
⋮    ⋮        ⋮        ⋮        ⋮        ⋮               ⋮          ⋮
4848 STIMATE  3        STIMATE  52836219 3:52859449:C:T  3          52859449
4849 TRIM38   6        TRIM38   25962802 6:25885586:C:T  6          25885586
4850 NDUFAF6  8        NDUFAF6  94895533 8:94914662:C:T  8          94914662
4851 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4852 TMEM273  10       TMEM273  49154725 10:49178453:A:G 10         49178453
4853 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4854 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4855 TMEM273  10       TMEM273  49154725 10:49197977:A:G 10         49197977
4856 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4857 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4858 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4859 RRM1     11       RRM1     4094707  11:4094744:C:A  11         4094744
4860 TMEM273  10       TMEM273  49154725 10:49201054:G:A 10         49201054
4861 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4862 TMEM273  10       TMEM273  49154725 10:49175232:C:T 10         49175232
4863 TMEM273  10       TMEM273  49154725 10:49178453:A:G 10         49178453
4864 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4865 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4866 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4867 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4868 TMEM273  10       TMEM273  49154725 10:49179907:C:T 10         49179907
4869 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4870 TMEM273  10       TMEM273  49154725 10:49184968:C:T 10         49184968
4871 TMEM273  10       TMEM273  49154725 10:49184350:A:T 10         49184350
4872 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4873 TMEM273  10       TMEM273  49154725 10:49194752:G:A 10         49194752
4874 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
4875 TMEM273  10       TMEM273  49154725 10:49179907:C:T 10         49179907
4876 TMEM273  10       TMEM273  49154725 10:49178453:A:G 10         49178453
4877 STIM1    11       STIM1    3854527  11:4091970:A:G  11         4091970
     A1 A2 Freq     ⋯ se_eQTL   p_eQTL        b_SMR     se_SMR    p_SMR
1    A  G  0.373231 ⋯ 0.0269378  2.049959e-11 0.439318  0.0896947 9.685428e-07
2    C  T  0.214623 ⋯ 0.0556689  6.954282e-09 0.675561  0.123167  4.136912e-08
3    T  C  0.317217 ⋯ 0.0335252  3.572675e-11 0.418898  0.0813193 2.587186e-07
4    T  A  0.474057 ⋯ 0.02637    2.400999e-10 0.565424  0.109266  2.282152e-07
5    C  T  0.416863 ⋯ 0.0485434  3.064873e-09 0.588746  0.105879  2.688908e-08
6    A  G  0.373231 ⋯ 0.0269378  2.049959e-11 0.441534  0.0900136 9.333410e-07
7    C  T  0.214623 ⋯ 0.0556689  6.954282e-09 0.671089  0.122463  4.254331e-08
8    T  C  0.317217 ⋯ 0.0335252  3.572675e-11 0.419848  0.0814952 2.579774e-07
9    T  A  0.474057 ⋯ 0.02637    2.400999e-10 0.567361  0.109584  2.250008e-07
10   C  T  0.416863 ⋯ 0.0485434  3.064873e-09 0.590664  0.106207  2.675626e-08
11   T  C  0.477594 ⋯ 0.027996   1.802509e-13 0.376462  0.0785554 1.648725e-06
12   A  G  0.373231 ⋯ 0.0269378  2.049959e-11 0.484473  0.101813  1.950940e-06
13   T  G  0.443396 ⋯ 0.0331269  6.177476e-23 -0.188774 0.0428156 1.038555e-05
14   T  G  0.442807 ⋯ 0.0322607  4.995413e-22 -0.198521 0.0451209 1.083777e-05
15   C  T  0.214623 ⋯ 0.0556689  6.954282e-09 0.676563  0.125616  7.206063e-08
16   T  C  0.317217 ⋯ 0.0335252  3.572675e-11 0.430418  0.0883696 1.112274e-06
17   T  A  0.474057 ⋯ 0.02637    2.400999e-10 0.574092  0.11693   9.120518e-07
18   C  T  0.416863 ⋯ 0.0485434  3.064873e-09 0.578581  0.106634  5.767708e-08
19   T  C  0.367925 ⋯ 0.0391833  2.065073e-62 0.13658   0.022843  2.244320e-09
20   G  C  0.336085 ⋯ 0.030431   5.606628e-12 0.624131  0.147996  2.473404e-05
21   C  T  0.443986 ⋯ 0.0301609  1.120737e-10 0.636457  0.156881  4.972174e-05
22   C  A  0.40566  ⋯ 0.0344464  3.709591e-31 -0.302765 0.0651036 3.311136e-06
23   G  A  0.344929 ⋯ 0.040571   1.251295e-71 0.18601   0.0349227 1.002241e-07
24   C  T  0.488797 ⋯ 0.041426   5.810314e-21 0.435964  0.076102  1.012155e-08
25   A  C  0.364976 ⋯ 0.0381273  7.899433e-13 0.47244   0.110003  1.748643e-05
26   A  G  0.49941  ⋯ 0.0346254  9.007571e-10 -0.530885 0.141093  1.681075e-04
27   C  T  0.276533 ⋯ 0.0407688  1.351728e-69 -0.157215 0.0368607 1.998089e-05
28   A  T  0.363208 ⋯ 0.0387865  3.861851e-23 0.32329   0.0709741 5.237522e-06
29   G  C  0.349057 ⋯ 0.0360552 6.100915e-201 -0.123088 0.0225684 4.924273e-08
30   C  A  0.346698 ⋯ 0.0421646  2.332436e-71 -0.177138 0.0336537 1.413070e-07
⋮    ⋮  ⋮  ⋮        ⋱ ⋮         ⋮             ⋮         ⋮         ⋮
4848 T  C  0.334906 ⋯ 0.0420158 1.444785e-14  -0.062593 0.0157569 7.114477e-05
4849 T  C  0.120283 ⋯ 0.0406169 9.815974e-10  -0.130868 0.0362982 3.117227e-04
4850 C  T  0.326061 ⋯ 0.0404412 5.772374e-11  -0.106996 0.0239698 8.053247e-06
4851 G  A  0.198703 ⋯ 0.0564164 2.228987e-11  0.317946  0.0728632 1.279342e-05
4852 G  A  0.323703 ⋯ 0.0443306 1.732503e-35  -0.150248 0.031524  1.877774e-06
4853 G  A  0.198703 ⋯ 0.0548807 1.022557e-13  0.293984  0.0645772 5.302631e-06
4854 G  A  0.198703 ⋯ 0.0577369 1.810570e-12  0.294887  0.0661397 8.251366e-06
4855 G  A  0.324292 ⋯ 0.0403532 8.947118e-44  -0.142436 0.0304188 2.834270e-06
4856 G  A  0.198703 ⋯ 0.0473334 1.084449e-50  0.169313  0.0315102 7.732586e-08
4857 G  A  0.198703 ⋯ 0.0501984 1.326607e-21  0.250386  0.0507895 8.227791e-07
4858 G  A  0.198703 ⋯ 0.044871  1.805739e-34  0.218425  0.0419275 1.892541e-07
4859 A  C  0.274764 ⋯ 0.0451621 2.442282e-34  0.148546  0.0326673 5.435713e-06
4860 G  A  0.327241 ⋯ 0.0435582 1.363077e-16  -0.223161 0.0521915 1.904404e-05
4861 G  A  0.198703 ⋯ 0.0526966 2.953813e-25  0.21932   0.0435621 4.787075e-07
4862 C  T  0.329599 ⋯ 0.0437505 2.888470e-16  -0.231653 0.0530111 1.243084e-05
4863 G  A  0.323703 ⋯ 0.0422043 4.882402e-16  -0.241809 0.0555318 1.334153e-05
4864 G  A  0.198703 ⋯ 0.0472023 4.231831e-21  0.269696  0.0548943 8.969356e-07
4865 G  A  0.198703 ⋯ 0.0475002 4.800520e-58  0.157302  0.0290274 5.990957e-08
4866 G  A  0.198703 ⋯ 0.0528402 1.633586e-29  0.201324  0.0392629 2.934739e-07
4867 G  A  0.198703 ⋯ 0.0521187 4.085228e-10  0.36836   0.0869906 2.290799e-05
4868 T  C  0.323113 ⋯ 0.0398701 2.920299e-33  -0.177094 0.0367631 1.456123e-06
4869 G  A  0.198703 ⋯ 0.0566197 4.545269e-11  0.321859  0.0742628 1.463852e-05
4870 T  C  0.324292 ⋯ 0.0479124 6.909639e-32  -0.150674 0.0314185 1.620901e-06
4871 T  A  0.324292 ⋯ 0.0443085 6.333231e-52  -0.126302 0.025441  6.887965e-07
4872 G  A  0.198703 ⋯ 0.0427093 2.489104e-84  0.144403  0.0261592 3.387314e-08
4873 A  G  0.324882 ⋯ 0.043773  4.954442e-22  -0.188883 0.0427437 9.917484e-06
4874 G  A  0.198703 ⋯ 0.0498813 4.400645e-39  0.183958  0.0349146 1.373176e-07
4875 T  C  0.323113 ⋯ 0.0465496 2.803932e-26  -0.171856 0.0364799 2.465379e-06
4876 G  A  0.323703 ⋯ 0.0501115 2.722787e-21  -0.174448 0.0384958 5.853431e-06
4877 G  A  0.198703 ⋯ 0.054685  6.940174e-12  0.319945  0.0725595 1.036486e-05
     p_HEIDI    nsnp_HEIDI disease
1    0.01504522 20         274
2    0.35817250 20         274
3    0.05148793 20         274
4    0.07245705 20         274
5    0.06904124 20         274
6    0.01504935 20         274.1
7    0.34679310 20         274.1
8    0.05228874 20         274.1
9    0.07100712 20         274.1
10   0.07457740 20         274.1
11   0.01112517 20         274.11
12   0.04439163 20         274.11
13   0.35008090 20         274.11
14   0.55021190 20         274.11
15   0.32126770 20         274.11
16   0.16065020 20         274.11
17   0.10612980 20         274.11
18   0.04985204 20         274.11
19   0.31358030 20         580
20   0.21496530 20         696
21   0.34981750 20         696
22   0.05152815 20         696
23   0.22561410 20         696
24   0.19830380 20         696
25   0.24892330 20         696
26   0.28884080 16         696
27   0.01582166 20         696
28   0.11019660 20         696
29   0.39581600 20         696
30   0.27468010 20         696
⋮    ⋮          ⋮          ⋮
4848 0.41062850 20         Uric_acid
4849 0.01359028 12         Uric_acid
4850 0.39883050 20         Uric_acid
4851 0.15166210 20         Urt
4852 0.72358280 20         Urt
4853 0.01692491 20         Urt
4854 0.10463920 20         Urt
4855 0.57801770 20         Urt
4856 0.01343190 20         Urt
4857 0.06072036 20         Urt
4858 0.07467014 20         Urt
4859 0.02774686 20         Urt
4860 0.25044040 20         Urt
4861 0.01283862 20         Urt
4862 0.66169890 20         Urt
4863 0.35211320 20         Urt
4864 0.01423453 20         Urt
4865 0.05611755 20         Urt
4866 0.01906421 20         Urt
4867 0.44283150 4          Urt
4868 0.34625600 20         Urt
4869 0.01647584 20         Urt
4870 0.39296700 20         Urt
4871 0.68595250 20         Urt
4872 0.01992881 20         Urt
4873 0.23456980 20         Urt
4874 0.03987792 20         Urt
4875 0.72116850 20         Urt
4876 0.91260640 20         Urt
4877 0.02538694 20         Urt
     celltype                                     q_SMR
1    eQTLsmr_CD56dim NK cells                     3.474427e-03
2    eQTLsmr_Core NDNs                            1.920501e-04
3    eQTLsmr_GZMB+ CD8+ Tem                       1.074635e-03
4    eQTLsmr_HLA-DRhi CD8+ Tem                    1.000597e-03
5    eQTLsmr_Tfh                                  1.326304e-04
6    eQTLsmr_CD56dim NK cells                     3.348149e-03
7    eQTLsmr_Core NDNs                            1.975011e-04
8    eQTLsmr_GZMB+ CD8+ Tem                       1.071557e-03
9    eQTLsmr_HLA-DRhi CD8+ Tem                    9.865035e-04
10   eQTLsmr_Tfh                                  1.319753e-04
11   eQTLsmr_Adaptive NK cells                    6.505869e-03
12   eQTLsmr_CD56dim NK cells                     7.331818e-03
13   eQTLsmr_Core classical monocytes             3.713370e-02
14   eQTLsmr_Core NDNs                            3.713370e-02
15   eQTLsmr_Core NDNs                            3.554391e-04
16   eQTLsmr_GZMB+ CD8+ Tem                       4.620035e-03
17   eQTLsmr_HLA-DRhi CD8+ Tem                    3.998840e-03
18   eQTLsmr_Tfh                                  3.034583e-04
19   eQTLsmr_Non-classical monocytes              1.771217e-04
20   eQTLsmr_Adaptive NK cells                    6.276561e-03
21   eQTLsmr_Adaptive NK cells                    1.003591e-02
22   eQTLsmr_Adaptive NK cells                    1.353963e-03
23   eQTLsmr_Adaptive NK cells                    9.645959e-05
24   eQTLsmr_Adaptive NK cells                    1.901887e-05
25   eQTLsmr_Adaptive NK cells                    5.130220e-03
26   eQTLsmr_Adaptive NK cells                    2.632350e-02
27   eQTLsmr_Adaptive NK cells                    5.475319e-03
28   eQTLsmr_ALPL- MARCKS- NDNs                   1.968311e-03
29   eQTLsmr_ALPL- MARCKS- NDNs                   6.168629e-05
30   eQTLsmr_ALPL- MARCKS- NDNs                   1.239105e-04
⋮    ⋮                                            ⋮
4848 eQTLsmr_VIM- FLNA- NDNs                      0.0073868266
4849 eQTLsmr_VIM- FLNA- NDNs                      0.0238198714
4850 eQTLsmr_VIM- FLNA- NDNs                      0.0011970711
4851 eQTLsmr_CD1C+ cDC2                           0.0292280731
4852 eQTLsmr_CD27- Th17                           0.0066299932
4853 eQTLsmr_CD27- Th17                           0.0162396107
4854 eQTLsmr_CD27+ Th1                            0.0228907627
4855 eQTLsmr_CD27+ Th17                           0.0091732329
4856 eQTLsmr_CD27+ Th17                           0.0008049246
4857 eQTLsmr_CD56bright NK cells                  0.0035506118
4858 eQTLsmr_Core classical monocytes             0.0012250576
4859 eQTLsmr_Core classical monocytes             0.0162396107
4860 eQTLsmr_GZMB+ CD4+ terminal effector T cells 0.0399806458
4861 eQTLsmr_GZMB+ Vδ2+ T cells                  0.0026560402
4862 eQTLsmr_GZMK+ CD8+ Tem                       0.0292280731
4863 eQTLsmr_HLA-DRhi CD8+ Tem                    0.0296094293
4864 eQTLsmr_Naïve B cells                        0.0036669088
4865 eQTLsmr_Naïve CD4+ T cells                   0.0008049246
4866 eQTLsmr_Naïve CD8+ T cells                   0.0017535517
4867 eQTLsmr_Non-classical monocytes              0.0468269458
4868 eQTLsmr_Non-switched memory B cells          0.0056553633
4869 eQTLsmr_Non-switched memory B cells          0.0315854533
4870 eQTLsmr_Switched Memory B cells              0.0059955584
4871 eQTLsmr_Tfh                                  0.0033439779
4872 eQTLsmr_Tfh                                  0.0008049246
4873 eQTLsmr_Th1_Th17                             0.0248503356
4874 eQTLsmr_Th1_Th17                             0.0010666419
4875 eQTLsmr_Th2                                  0.0083262280
4876 eQTLsmr_Th22                                 0.0168398874
4877 eQTLsmr_vNKT                                 0.0251597259

In [11]:
table(sub_smr_all$disease)

                                  274                                 274.1
                                    5                                     5
                               274.11                                   580
                                    8                                     1
                                  696                                 696.4
                                  201                                   204
                               696.41                                 714.1
                                  192                                    56
                                   AD                                    As
                                  174                                   298
                               Asthma                     Atopic_dermatitis
                                  250                                    76
                        Breast_cancer                                   CHB
                                  130                                    32
                                  CHC                   Chronic_hepatitis_B
                                    3                                    25
                  Chronic_hepatitis_C Chronic_obstructive_pulmonary_disease
                                    2                                    31
                    Chronic_sinusitis                                   ChS
                                   59                                    62
                            Cirrhosis                     Colorectal_cancer
                                   31                                     9
                                 COPD               Coronary_artery_disease
                                   46                                   242
                    Esophageal_cancer                        Gastric_cancer
                                   62                                     8
                                   GD                        Graves_disease
                                  166                                    73
                                   HD                        Hepatic_cancer
                                   26                                    21
             Hepatocellular_carcinoma                                  Hype
                                   26                                    89
                                 Hypo                           Lung_cancer
                                   12                                    12
                Myocardial_infarction                    Nephrotic_syndrome
                                  195                                     3
                                   NS             Peripheral_artery_disease
                                    5                                     5
                                   Pn                             Pneumonia
                                    4                                     3
                                  Pol                                    PT
                                   12                                    60
                                   RA                  Rheumatoid_arthritis
                                  265                                   347
                                  T1D                                   T2D
                                   51                                   431
                      Type_1_diabetes                       Type_2_diabetes
                                   49                                   581
                                   UC                    Ulcerative_colitis
                                    4                                     4
                            Uric_acid                                   Urt
                                  194                                    27

In [12]:
write.csv(sub_smr_all,'/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/SMR_eQTL_disease.csv')

### eQTL-pQTL2

In [18]:
SMR_dir <- "/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/eQTL_pQTL_SMR/"
disease_dirs <- list.dirs(SMR_dir, full.names = TRUE, recursive = FALSE)
all_smr_list <- list()

In [19]:
# 遍历每个疾病文件夹
for (disease_path in disease_dirs) {
  disease_name <- basename(disease_path)  # 疾病名
  # 找出该疾病下所有smr文件
  smr_files <- list.files(disease_path, pattern = "\\.smr$", full.names = TRUE)
  if (length(smr_files) == 0) next
  # 读取每个smr文件
  for (f in smr_files) {
    # 提取细胞类型名（假设文件名类似 CD4_Tcells.smr 或 Mono.smr）
    celltype <- str_remove(basename(f), "\\.smr$")
    # 读取smr文件
    smr_df <- tryCatch({
      read.table(f, header = TRUE, sep = "\t", stringsAsFactors = FALSE, colClasses = "character")
    }, error = function(e) {
      message("Failed to read ", f)
      return(NULL)
    })
    # 跳过空文件
    if (is.null(smr_df) || nrow(smr_df) == 0) next
    # 添加疾病和细胞类型信息
    smr_df$disease <- disease_name
    smr_df$celltype <- celltype
    # 存入列表
    all_smr_list[[length(all_smr_list) + 1]] <- smr_df
  }
}

In [20]:
all_smr <- rbindlist(all_smr_list, fill = TRUE)
all_smr

        probeID     ProbeChr Gene        Probe_bp  topSNP          topSNP_chr
1       LINC00115   1        LINC00115   824228    1:928209:C:T    1
2       LINC01128   1        LINC01128   825138    1:928209:C:T    1
3       HES4        1        HES4        998962    1:1000112:G:T   1
4       TNFRSF18    1        TNFRSF18    1203508   1:1217733:G:A   1
5       TNFRSF4     1        TNFRSF4     1211326   1:1217251:C:A   1
6       SDF4        1        SDF4        1216931   1:1232416:C:T   1
7       B3GALT6     1        B3GALT6     1232237   1:1240390:G:A   1
8       CPTP        1        CPTP        1324756   1:1363031:C:T   1
9       MRPL20-AS1  1        MRPL20-AS1  1399515   1:1399922:C:T   1
10      SSU72       1        SSU72       1541673   1:1531589:C:T   1
11      MMP23B      1        MMP23B      1632163   1:1627515:C:T   1
12      SLC35E2B    1        SLC35E2B    1659529   1:1639348:G:T   1
13      CDK11A      1        CDK11A      1702379   1:1684817:G:C   1
14      PRKCZ       1        PRKCZ       2050411   1:2050397:C:T   1
15      PLCH2       1        PLCH2       2425980   1:2423124:C:T   1
16      TNFRSF14    1        TNFRSF14    2555639   1:2557491:G:A   1
17      WRAP73      1        WRAP73      3630767   1:3602179:C:T   1
18      C1orf174    1        C1orf174    3889125   1:3904770:G:A   1
19      KCNAB2      1        KCNAB2      5990927   1:6013459:G:C   1
20      UTS2        1        UTS2        7843083   1:7931143:G:A   1
21      TNFRSF9     1        TNFRSF9     7915871   1:7931143:G:A   1
22      PARK7       1        PARK7       7954291   1:7905307:G:A   1
23      H6PD        1        H6PD        9234774   1:9235735:G:C   1
24      SPSB1       1        SPSB1       9292894   1:9278554:C:T   1
25      CENPS       1        CENPS       10430433  1:10431152:G:A  1
26      FBXO2       1        FBXO2       11637018  1:11656698:G:A  1
27      FBXO6       1        FBXO6       11664200  1:11665661:G:A  1
28      DRAXIN      1        DRAXIN      11691710  1:11691078:C:T  1
29      AGTRAP      1        AGTRAP      11736084  1:11740646:C:T  1
30      MTHFR       1        MTHFR       11785723  1:11790946:G:C  1
⋮       ⋮           ⋮        ⋮           ⋮         ⋮               ⋮
6425637 PPIA        7        PPIA        44796680  7:44774573:G:A  7
6425638 FGL2        7        FGL2        77193369  7:77199636:C:T  7
6425639 SAMD9L      7        SAMD9L      93130056  7:93161614:C:T  7
6425640 ARPC1B      7        ARPC1B      99374249  7:99431654:C:T  7
6425641 COG5        7        COG5        107201372 7:107446849:C:T 7
6425642 BPGM        7        BPGM        134646811 7:134627246:C:T 7
6425643 TRBV28      7        TRBV28      142720660 7:142714038:C:T 7
6425644 TRBC1       7        TRBC1       142791694 7:142783765:G:C 7
6425645 MYOM2       8        MYOM2       2045046   8:2137125:C:T   8
6425646 CSGALNACT1  8        CSGALNACT1  19404161  8:19466474:C:A  8
6425647 MSC         8        MSC         71841560  8:71863643:T:A  8
6425648 TERF1       8        TERF1       73008856  8:73197630:G:A  8
6425649 PAG1        8        PAG1        80967810  8:81135593:C:A  8
6425650 CPQ         8        CPQ         96645242  8:96617678:G:A  8
6425651 MTSS1       8        MTSS1       124550784 8:124564869:C:T 8
6425652 LRATD2      8        LRATD2      126552443 8:126483446:T:A 8
6425653 LY6E        8        LY6E        143017982 8:143004155:G:A 8
6425654 CPSF1       8        CPSF1       144393229 8:144371817:C:T 8
6425655 RPL8        8        RPL8        144789765 8:144763522:G:T 8
6425656 TTC39B      9        TTC39B      15163622  9:15301430:C:A  9
6425657 B4GALT1     9        B4GALT1     33104082  9:33137305:C:T  9
6425658 NUDT2       9        NUDT2       34329506  9:34151465:C:T  9
6425659 GRHPR       9        GRHPR       37422666  9:37422659:C:T  9
6425660 NMRK1       9        NMRK1       75060573  9:75093064:C:T  9
6425661 GNAQ        9        GNAQ        77716097  9:77874687:C:T  9
6425662 SYK         9        SYK         90801787  9:90776258:C:A  9
6425663 ERCC6L2-AS1 9        ERCC6L2-AS1 95759231  9:95787982:C:T  9
6425664 STOM        9        STOM        121338987 9:121338684:G:C 9
6425665 RPL12       9        RPL12       127447674 9:127458419:C:A 9
6425666 DNLZ        9        DNLZ        136359480 9:136365763:G:A 9
        topSNP_bp A1 A2 Freq     ⋯ b_eQTL    se_eQTL   p_eQTL       b_SMR
1       928209    T  C  0.106132 ⋯ 0.675476  0.0736853 4.862338e-20 -0.330138
2       928209    T  C  0.106132 ⋯ 0.84287   0.069478  7.195198e-34 -0.264572
3       1000112   G  T  0.126179 ⋯ 0.580657  0.0654351 7.069643e-19 -0.0247995
4       1217733   A  G  0.268278 ⋯ -0.721839 0.0438161 5.615836e-61 -0.0131608
5       1217251   A  C  0.266509 ⋯ -0.653871 0.0426808 5.620573e-53 0.004741
6       1232416   T  C  0.225236 ⋯ -0.331675 0.040547  2.838453e-16 -0.051255
7       1240390   A  G  0.223467 ⋯ -0.35543  0.0397387 3.747308e-19 -0.0548631
8       1363031   C  T  0.17158  ⋯ 0.810526  0.0464073 2.624344e-68 -0.020974
9       1399922   T  C  0.113208 ⋯ -0.561624 0.0538927 1.985297e-25 0.0254619
10      1531589   T  C  0.145047 ⋯ -0.423304 0.0552726 1.881594e-14 -0.0153554
11      1627515   C  T  0.418632 ⋯ 0.287306  0.0389339 1.590814e-13 -0.00452479
12      1639348   T  G  0.419811 ⋯ 0.283506  0.0396588 8.765670e-13 -0.0190472
13      1684817   G  C  0.494693 ⋯ 0.405374  0.0444673 7.778590e-20 0.00567377
14      2050397   C  T  0.326061 ⋯ -0.47118  0.0415283 7.762298e-30 -0.0413854
15      2423124   T  C  0.134434 ⋯ 0.691389  0.0568604 5.112411e-34 -0.0313861
16      2557491   A  G  0.494104 ⋯ 0.383624  0.0356451 5.184830e-27 -0.00573478
17      3602179   T  C  0.410967 ⋯ 0.243495  0.0386934 3.115242e-10 -0.0924044
18      3904770   G  A  0.393278 ⋯ -0.276901 0.041004  1.447969e-11 0.0353917
19      6013459   G  C  0.284198 ⋯ -0.282942 0.0418116 1.314119e-11 0.106029
20      7931143   A  G  0.373821 ⋯ -0.847733 0.0462318 4.227057e-75 0.00235923
21      7931143   A  G  0.373821 ⋯ 0.57116   0.0443719 6.459902e-38 -0.00350164
22      7905307   G  A  0.271226 ⋯ 0.251246  0.0406864 6.608653e-10 -0.0346274
23      9235735   G  C  0.462264 ⋯ 0.584754  0.0348038 2.382928e-63 -0.0193244
24      9278554   T  C  0.118514 ⋯ 0.741189  0.0604461 1.449192e-34 -0.00107935
25      10431152  A  G  0.161557 ⋯ 0.347571  0.0577348 1.742743e-09 0.0584053
26      11656698  A  G  0.150354 ⋯ 0.828395  0.0571691 1.396047e-47 0.00748435
27      11665661  A  G  0.414505 ⋯ -0.322673 0.0303268 1.943719e-26 -0.0365695
28      11691078  T  C  0.120873 ⋯ -0.394347 0.0644529 9.453119e-10 0.0109041
29      11740646  T  C  0.345519 ⋯ 0.25989   0.033811  1.511609e-14 -0.0230867
30      11790946  C  G  0.211675 ⋯ 0.403833  0.0392973 9.007430e-25 0.0217912
⋮       ⋮         ⋮  ⋮  ⋮        ⋱ ⋮         ⋮         ⋮            ⋮
6425637 44774573  A  G  0.213443 ⋯ -0.316078 0.0529328 2.353470e-09 0.0531514
6425638 77199636  T  C  0.258255 ⋯ 0.760584  0.0480165 1.646282e-56 -0.00433877
6425639 93161614  T  C  0.141509 ⋯ -0.443249 0.0534777 1.147105e-16 -0.0708406
6425640 99431654  T  C  0.35967  ⋯ -0.446763 0.0441117 4.150656e-24 0.0273075
6425641 107446849 T  C  0.34375  ⋯ 0.474654  0.0420273 1.405470e-29 -0.0179078
6425642 134627246 T  C  0.114976 ⋯ -0.62075  0.062655  3.864400e-23 -0.0307692
6425643 142714038 T  C  0.31191  ⋯ -0.370472 0.0485598 2.362493e-14 -0.00836771
6425644 142783765 C  G  0.136792 ⋯ 0.602029  0.0648751 1.697805e-20 0.0702624
6425645 2137125   T  C  0.426297 ⋯ 0.823219  0.0424984 1.366318e-83 0.0225942
6425646 19466474  C  A  0.145637 ⋯ 0.370371  0.0582171 1.992934e-10 0.0610199
6425647 71863643  A  T  0.367335 ⋯ 0.234589  0.0417314 1.894149e-08 0.0426278
6425648 73197630  A  G  0.301887 ⋯ -0.270979 0.0466063 6.092307e-09 0.0332129
6425649 81135593  A  C  0.195165 ⋯ 0.304777  0.0540033 1.664593e-08 0.0593877
6425650 96617678  G  A  0.397406 ⋯ -0.293659 0.0423179 3.938895e-12 -0.0357557
6425651 124564869 C  T  0.449882 ⋯ 0.269979  0.0406    2.936048e-11 -0.0496334
6425652 126483446 A  T  0.306604 ⋯ -0.292366 0.0450947 8.969838e-11 -0.00376241
6425653 143004155 A  G  0.466392 ⋯ -0.326484 0.0437563 8.559880e-14 -0.0174588
6425654 144371817 T  C  0.321344 ⋯ 0.349634  0.0437726 1.377022e-15 -0.0102965
6425655 144763522 G  T  0.32783  ⋯ -0.351088 0.0480967 2.885401e-13 0.0301918
6425656 15301430  A  C  0.288915 ⋯ -0.298866 0.0459686 7.950977e-11 -0
6425657 33137305  C  T  0.417453 ⋯ -0.337427 0.043558  9.436281e-15 -0.0391195
6425658 34151465  C  T  0.465802 ⋯ -0.269972 0.0429083 3.137322e-10 -0.0292623
6425659 37422659  T  C  0.435731 ⋯ 0.346749  0.0401858 6.207924e-18 0.0181688
6425660 75093064  T  C  0.466981 ⋯ -0.375368 0.0449654 6.947345e-17 -0.0149187
6425661 77874687  T  C  0.192217 ⋯ 0.34971   0.0488935 8.523036e-13 -0.26908
6425662 90776258  A  C  0.423349 ⋯ -0.29954  0.0421052 1.126505e-12 0.0313814
6425663 95787982  T  C  0.370283 ⋯ -0.334448 0.0424914 3.519444e-15 -0.00538201
6425664 121338684 C  G  0.145047 ⋯ -0.341443 0.0577796 3.433411e-09 0.0834692
6425665 127458419 A  C  0.396226 ⋯ 0.345311  0.0449684 1.603802e-14 -0.0422807
6425666 136365763 A  G  0.105542 ⋯ 0.692577  0.064488  6.631660e-27 0.0360971
        se_SMR    p_SMR        p_HEIDI      nsnp_HEIDI
1       0.209492  1.150494e-01 2.657829e-02 16
2       0.166819  1.127430e-01 2.984633e-02 18
3       0.0270111 3.585545e-01 1.589803e-01 11
4       0.0256414 6.077665e-01 4.936223e-01 20
5       0.0321179 8.826488e-01 7.801704e-01 20
6       0.0624243 4.116036e-01 7.170661e-02 19
7       0.0582817 3.465283e-01 3.902540e-02 20
8       0.0286486 4.640986e-01 1.843850e-01 12
9       0.0392483 5.165069e-01 6.575267e-01 15
10      0.0510666 7.636479e-01 9.427311e-01 10
11      0.0487324 9.260229e-01 1.501963e-01 17
12      0.0536806 7.227205e-01 1.617020e-01 8
13      0.0340483 8.676542e-01 1.524671e-01 20
14      0.0349968 2.369881e-01 6.877071e-01 20
15      0.0263061 2.328265e-01 9.507714e-01 7
16      0.0310245 8.533493e-01 7.997517e-01 20
17      0.0549758 9.279799e-02 5.771942e-01 20
18      0.049753  4.768682e-01 5.906155e-01 5
19      0.0717116 1.392622e-01 3.257099e-01 10
20      0.014038  8.665359e-01 4.027735e-01 19
21      0.0208366 8.665417e-01 3.937318e-01 19
22      0.0484853 4.751138e-01 5.200105e-01 7
23      0.0207244 3.511066e-01 1.246763e-01 16
24      0.021722  9.603702e-01 7.611317e-01 3
25      0.0620456 3.465364e-01 5.396369e-03 17
26      0.029097  7.970083e-01 7.648675e-01 13
27      0.0398172 3.583917e-01 2.953267e-01 11
28      0.0535358 8.386047e-01 NA           NA
29      0.0501113 6.450076e-01 2.973333e-02 5
30      0.0325084 5.026506e-01 4.189282e-01 20
⋮       ⋮         ⋮            ⋮            ⋮
6425637 0.0386868 1.694761e-01 1.737888e-01 4
6425638 0.0256396 8.656227e-01 4.037225e-01 20
6425639 0.059054  2.302984e-01 6.831090e-01 10
6425640 0.0350218 4.355497e-01 2.270576e-01 17
6425641 0.0270136 5.073833e-01 1.052571e-01 20
6425642 0.0714328 6.666548e-01 2.707693e-01 12
6425643 0.0316004 7.911654e-01 1.632762e-01 16
6425644 0.0271554 9.669764e-03 7.935642e-02 3
6425645 0.0187434 2.280292e-01 5.540721e-01 20
6425646 0.0397835 1.250787e-01 1.488395e-02 20
6425647 0.0559326 4.459834e-01 1.558750e-01 9
6425648 0.0486796 4.950643e-01 2.075898e-01 7
6425649 0.0622521 3.400907e-01 3.362301e-01 3
6425650 0.0469364 4.461847e-01 6.627277e-01 7
6425651 0.0468976 2.899023e-01 7.282332e-01 15
6425652 0.0584913 9.487120e-01 4.085724e-01 4
6425653 0.0414158 6.733551e-01 8.902591e-01 11
6425654 0.0392051 7.928345e-01 2.809633e-01 20
6425655 0.0338633 3.726184e-01 2.466682e-01 20
6425656 0.0411556 1.000000e+00 7.597808e-01 20
6425657 0.0356266 2.721853e-01 8.971774e-01 4
6425658 0.0435867 5.019920e-01 8.021212e-01 15
6425659 0.0361106 6.148641e-01 5.296210e-02 3
6425660 0.0368074 6.852434e-01 4.085484e-01 20
6425661 0.1916    1.602036e-01 2.102244e-01 20
6425662 0.0449521 4.851104e-01 1.422000e-01 20
6425663 0.0346908 8.767092e-01 5.457976e-01 19
6425664 0.123816  5.002214e-01 6.599962e-01 9
6425665 0.0391943 2.807003e-01 3.555529e-01 13
6425666 0.0507916 4.772767e-01 2.915407e-01 20
        disease
1       adenosine_deaminase_measurement
2       adenosine_deaminase_measurement
3       adenosine_deaminase_measurement
4       adenosine_deaminase_measurement
5       adenosine_deaminase_measurement
6       adenosine_deaminase_measurement
7       adenosine_deaminase_measurement
8       adenosine_deaminase_measurement
9       adenosine_deaminase_measurement
10      adenosine_deaminase_measurement
11      adenosine_deaminase_measurement
12      adenosine_deaminase_measurement
13      adenosine_deaminase_measurement
14      adenosine_deaminase_measurement
15      adenosine_deaminase_measurement
16      adenosine_deaminase_measurement
17      adenosine_deaminase_measurement
18      adenosine_deaminase_measurement
19      adenosine_deaminase_measurement
20      adenosine_deaminase_measurement
21      adenosine_deaminase_measurement
22      adenosine_deaminase_measurement
23      adenosine_deaminase_measurement
24      adenosine_deaminase_measurement
25      adenosine_deaminase_measurement
26      adenosine_deaminase_measurement
27      adenosine_deaminase_measurement
28      adenosine_deaminase_measurement
29      adenosine_deaminase_measurement
30      adenosine_deaminase_measurement
⋮       ⋮
6425637 vascular_endothelial_growth_factor_A_measurement
6425638 vascular_endothelial_growth_factor_A_measurement
6425639 vascular_endothelial_growth_factor_A_measurement
6425640 vascular_endothelial_growth_factor_A_measurement
6425641 vascular_endothelial_growth_factor_A_measurement
6425642 vascular_endothelial_growth_factor_A_measurement
6425643 vascular_endothelial_growth_factor_A_measurement
6425644 vascular_endothelial_growth_factor_A_measurement
6425645 vascular_endothelial_growth_factor_A_measurement
6425646 vascular_endothelial_growth_factor_A_measurement
6425647 vascular_endothelial_growth_factor_A_measurement
6425648 vascular_endothelial_growth_factor_A_measurement
6425649 vascular_endothelial_growth_factor_A_measurement
6425650 vascular_endothelial_growth_factor_A_measurement
6425651 vascular_endothelial_growth_factor_A_measurement
6425652 vascular_endothelial_growth_factor_A_measurement
6425653 vascular_endothelial_growth_factor_A_measurement
6425654 vascular_endothelial_growth_factor_A_measurement
6425655 vascular_endothelial_growth_factor_A_measurement
6425656 vascular_endothelial_growth_factor_A_measurement
6425657 vascular_endothelial_growth_factor_A_measurement
6425658 vascular_endothelial_growth_factor_A_measurement
6425659 vascular_endothelial_growth_factor_A_measurement
6425660 vascular_endothelial_growth_factor_A_measurement
6425661 vascular_endothelial_growth_factor_A_measurement
6425662 vascular_endothelial_growth_factor_A_measurement
6425663 vascular_endothelial_growth_factor_A_measurement
6425664 vascular_endothelial_growth_factor_A_measurement
6425665 vascular_endothelial_growth_factor_A_measurement
6425666 vascular_endothelial_growth_factor_A_measurement
        celltype
1       pQTLsmr_Adaptive NK cells
2       pQTLsmr_Adaptive NK cells
3       pQTLsmr_Adaptive NK cells
4       pQTLsmr_Adaptive NK cells
5       pQTLsmr_Adaptive NK cells
6       pQTLsmr_Adaptive NK cells
7       pQTLsmr_Adaptive NK cells
8       pQTLsmr_Adaptive NK cells
9       pQTLsmr_Adaptive NK cells
10      pQTLsmr_Adaptive NK cells
11      pQTLsmr_Adaptive NK cells
12      pQTLsmr_Adaptive NK cells
13      pQTLsmr_Adaptive NK cells
14      pQTLsmr_Adaptive NK cells
15      pQTLsmr_Adaptive NK cells
16      pQTLsmr_Adaptive NK cells
17      pQTLsmr_Adaptive NK cells
18      pQTLsmr_Adaptive NK cells
19      pQTLsmr_Adaptive NK cells
20      pQTLsmr_Adaptive NK cells
21      pQTLsmr_Adaptive NK cells
22      pQTLsmr_Adaptive NK cells
23      pQTLsmr_Adaptive NK cells
24      pQTLsmr_Adaptive NK cells
25      pQTLsmr_Adaptive NK cells
26      pQTLsmr_Adaptive NK cells
27      pQTLsmr_Adaptive NK cells
28      pQTLsmr_Adaptive NK cells
29      pQTLsmr_Adaptive NK cells
30      pQTLsmr_Adaptive NK cells
⋮       ⋮
6425637 pQTLsmr_vNKT
6425638 pQTLsmr_vNKT
6425639 pQTLsmr_vNKT
6425640 pQTLsmr_vNKT
6425641 pQTLsmr_vNKT
6425642 pQTLsmr_vNKT
6425643 pQTLsmr_vNKT
6425644 pQTLsmr_vNKT
6425645 pQTLsmr_vNKT
6425646 pQTLsmr_vNKT
6425647 pQTLsmr_vNKT
6425648 pQTLsmr_vNKT
6425649 pQTLsmr_vNKT
6425650 pQTLsmr_vNKT
6425651 pQTLsmr_vNKT
6425652 pQTLsmr_vNKT
6425653 pQTLsmr_vNKT
6425654 pQTLsmr_vNKT
6425655 pQTLsmr_vNKT
6425656 pQTLsmr_vNKT
6425657 pQTLsmr_vNKT
6425658 pQTLsmr_vNKT
6425659 pQTLsmr_vNKT
6425660 pQTLsmr_vNKT
6425661 pQTLsmr_vNKT
6425662 pQTLsmr_vNKT
6425663 pQTLsmr_vNKT
6425664 pQTLsmr_vNKT
6425665 pQTLsmr_vNKT
6425666 pQTLsmr_vNKT

In [21]:
colnames(all_smr)

 [1] "probeID"    "ProbeChr"   "Gene"       "Probe_bp"   "topSNP"
 [6] "topSNP_chr" "topSNP_bp"  "A1"         "A2"         "Freq"
[11] "b_GWAS"     "se_GWAS"    "p_GWAS"     "b_eQTL"     "se_eQTL"
[16] "p_eQTL"     "b_SMR"      "se_SMR"     "p_SMR"      "p_HEIDI"
[21] "nsnp_HEIDI" "disease"    "celltype"

In [22]:
all_smr$p_GWAS <- as.numeric(all_smr$p_GWAS)
all_smr$p_eQTL <- as.numeric(all_smr$p_eQTL)
all_smr$p_SMR <- as.numeric(all_smr$p_SMR)
all_smr <- all_smr %>% group_by(disease) %>% mutate(q_SMR = p.adjust(p_SMR, method = "BH")) %>% ungroup()
all_smr$p_HEIDI <- as.numeric(all_smr$p_HEIDI)

In [23]:
sub_smr_all <- subset(all_smr, p_GWAS < 0.00001 & p_HEIDI > 0.01 & q_SMR < 0.05 & p_eQTL < 0.00000005)
sub_smr_all

    probeID  ProbeChr Gene     Probe_bp  topSNP          topSNP_chr topSNP_bp
1   ADA      20       ADA      44584896  20:44672026:G:A 20         44672026
2   ADA      20       ADA      44584896  20:44672026:G:A 20         44672026
3   ADA      20       ADA      44584896  20:44672026:G:A 20         44672026
4   ADA      20       ADA      44584896  20:44672026:G:A 20         44672026
5   CTSL     9        CTSL     87724051  9:87709162:C:T  9          87709162
6   CTSL     9        CTSL     87724051  9:87725948:C:A  9          87725948
7   CTSL     9        CTSL     87724051  9:87709162:C:T  9          87709162
8   CTLA4    2        CTLA4    203853888 2:203852990:G:T 2          203852990
9   LTB      6        LTB      31580525  6:31550577:G:A  6          31550577
10  TNF      6        TNF      31575565  6:31565601:G:A  6          31565601
11  LTB      6        LTB      31580525  6:31565601:G:A  6          31565601
12  CTLA4    2        CTLA4    203853888 2:203852990:G:T 2          203852990
13  CTLA4    2        CTLA4    203853888 2:203852990:G:T 2          203852990
14  NBEAL2   3        NBEAL2   46979666  3:46973459:C:T  3          46973459
15  CCL3-AS1 17       CCL3-AS1 36072866  17:36210711:C:A 17         36210711
16  NBEAL2   3        NBEAL2   46979666  3:46969630:G:C  3          46969630
17  NBEAL2   3        NBEAL2   46979666  3:46978582:G:A  3          46978582
18  NBEAL2   3        NBEAL2   46979666  3:47031776:C:T  3          47031776
19  CCL3L3   17       CCL3L3   36194869  17:36210711:C:A 17         36210711
20  SCAP     3        SCAP     47413681  3:47090105:G:A  3          47090105
21  CCR5AS   3        CCR5AS   46364391  3:46274661:C:T  3          46274661
22  NBEAL2   3        NBEAL2   46979666  3:46978582:G:A  3          46978582
23  CCL3L3   17       CCL3L3   36194869  17:36210711:C:A 17         36210711
24  NBEAL2   3        NBEAL2   46979666  3:46982458:C:T  3          46982458
25  CCL3L3   17       CCL3L3   36194869  17:36210711:C:A 17         36210711
26  CCL3-AS1 17       CCL3-AS1 36072866  17:36210711:C:A 17         36210711
27  CCL3L3   17       CCL3L3   36194869  17:36210711:C:A 17         36210711
28  CCL3-AS1 17       CCL3-AS1 36072866  17:36210711:C:A 17         36210711
29  CCL3L3   17       CCL3L3   36194869  17:36210711:C:A 17         36210711
30  NAAA     4        NAAA     75913660  4:75943306:G:A  4          75943306
⋮   ⋮        ⋮        ⋮        ⋮         ⋮               ⋮          ⋮
309 SARM1    17       SARM1    28364356  17:28393545:G:A 17         28393545
310 TMEM199  17       TMEM199  28357642  17:28393545:G:A 17         28393545
311 SARM1    17       SARM1    28364356  17:28393545:G:A 17         28393545
312 TMEM199  17       TMEM199  28357642  17:28395626:G:A 17         28395626
313 TMEM258  11       TMEM258  61768501  11:61838027:T:A 11         61838027
314 FADS2    11       FADS2    61792980  11:61814184:G:A 11         61814184
315 FADS1    11       FADS1    61799627  11:61800281:C:A 11         61800281
316 FADS2    11       FADS2    61792980  11:61803910:G:A 11         61803910
317 FADS1    11       FADS1    61799627  11:61813163:C:T 11         61813163
318 FADS1    11       FADS1    61799627  11:61813163:C:T 11         61813163
319 FADS2    11       FADS2    61792980  11:61829161:C:T 11         61829161
320 FADS1    11       FADS1    61799627  11:61792609:G:A 11         61792609
321 FADS1    11       FADS1    61799627  11:61852357:C:A 11         61852357
322 FADS2    11       FADS2    61792980  11:61814184:G:A 11         61814184
323 FADS1    11       FADS1    61799627  11:61814184:G:A 11         61814184
324 FADS1    11       FADS1    61799627  11:61803910:G:A 11         61803910
325 TMEM258  11       TMEM258  61768501  11:61792609:G:A 11         61792609
326 FADS2    11       FADS2    61792980  11:61852357:C:A 11         61852357
327 FADS2    11       FADS2    61792980  11:61814184:G:A 11         61814184
328 FADS1    11       FADS1    61799627  11:61837495:C:T 11         61837495
329 FADS1    11       FADS1    61799627  11:61813163:C:T 11         61813163
330 TMEM258  11       TMEM258  61768501  11:61792609:G:A 11         61792609
331 FADS2    11       FADS2    61792980  11:61800281:C:A 11         61800281
332 FADS3    11       FADS3    61873519  11:61813163:C:T 11         61813163
333 FADS1    11       FADS1    61799627  11:61852357:C:A 11         61852357
334 PSMD3    17       PSMD3    39980807  17:39981370:C:T 17         39981370
335 NAA38    17       NAA38    7856685   17:7847732:C:T  17         7847732
336 PARK7    1        PARK7    7954291   1:7905307:G:A   1          7905307
337 PARK7    1        PARK7    7954291   1:8032944:G:A   1          8032944
338 ABO      9        ABO      133233278 9:133251979:C:T 9          133251979
    A1 A2 Freq     ⋯ se_eQTL   p_eQTL       b_SMR     se_SMR    p_SMR
1   A  G  0.248821 ⋯ 0.047633  7.888813e-11 0.387417  0.0761698 3.652498e-07
2   A  G  0.248821 ⋯ 0.0445726 2.169461e-16 0.327829  0.0566241 7.056788e-09
3   A  G  0.248821 ⋯ 0.0430986 4.858822e-15 0.355572  0.0629222 1.595318e-08
4   A  G  0.248821 ⋯ 0.037901  7.806166e-09 0.548478  0.11637   2.438305e-06
5   T  C  0.366745 ⋯ 0.0444547 5.643760e-26 0.131681  0.0279213 2.403523e-06
6   A  C  0.302476 ⋯ 0.041719  2.241712e-30 0.151301  0.0281894 7.992178e-08
7   T  C  0.366745 ⋯ 0.0414953 6.321745e-78 0.0795696 0.0156779 3.869217e-07
8   T  G  0.202241 ⋯ 0.042559  2.319162e-12 -0.208375 0.0510714 4.502263e-05
9   G  A  0.251179 ⋯ 0.0298767 1.535739e-14 0.285294  0.0651807 1.203424e-05
10  G  A  0.313679 ⋯ 0.0386133 2.487999e-12 0.280277  0.0597506 2.721654e-06
11  G  A  0.313679 ⋯ 0.0325362 2.086339e-08 0.415672  0.0991506 2.761033e-05
12  T  G  0.202241 ⋯ 0.0358304 3.797080e-12 -0.249975 0.0614748 4.776623e-05
13  T  G  0.202241 ⋯ 0.0383358 9.034713e-14 -0.21766  0.0523017 3.159893e-05
14  T  C  0.451651 ⋯ 0.0321132 9.496247e-75 0.0970327 0.0214351 5.988091e-06
15  A  C  0.212854 ⋯ 0.0542846 5.132761e-09 0.501301  0.123557  4.965330e-05
16  G  C  0.451651 ⋯ 0.0390132 8.805350e-41 0.108302  0.0245674 1.041458e-05
17  G  A  0.451061 ⋯ 0.0390537 4.484448e-30 0.123378  0.0292693 2.494807e-05
18  C  T  0.429245 ⋯ 0.0313804 3.193430e-21 -0.180967 0.0447393 5.233872e-05
19  A  C  0.212854 ⋯ 0.0470056 2.034874e-16 0.411505  0.088503  3.325583e-06
20  G  A  0.436321 ⋯ 0.0300736 9.557265e-37 0.142331  0.0334571 2.098627e-05
21  C  T  0.225236 ⋯ 0.0497757 4.154312e-08 -0.415784 0.0919453 6.123419e-06
22  G  A  0.451061 ⋯ 0.0331889 3.295170e-57 0.103769  0.0237791 1.277817e-05
23  A  C  0.212854 ⋯ 0.0526933 1.542765e-21 0.316561  0.0652316 1.216828e-06
24  T  C  0.474057 ⋯ 0.0324937 4.760093e-28 0.152192  0.0366369 3.266338e-05
25  A  C  0.212854 ⋯ 0.0558519 7.141502e-11 0.436785  0.102432  2.006688e-05
26  A  C  0.212854 ⋯ 0.0563105 4.780078e-08 0.517214  0.131873  8.779384e-05
27  A  C  0.212854 ⋯ 0.0499004 2.952848e-13 0.436693  0.0978808 8.139565e-06
28  A  C  0.212854 ⋯ 0.0472271 4.813321e-09 0.575163  0.141637  4.889908e-05
29  A  C  0.212854 ⋯ 0.0529517 1.213819e-16 0.362573  0.0777936 3.151338e-06
30  A  G  0.408019 ⋯ 0.0336008 7.070784e-19 -0.259252 0.0530419 1.020297e-06
⋮   ⋮  ⋮  ⋮        ⋱ ⋮         ⋮            ⋮         ⋮         ⋮
309 G  A  0.291274 ⋯ 0.0394047 9.862610e-19 -0.254734 0.044272  8.723533e-09
310 G  A  0.291274 ⋯ 0.0394585 1.947294e-15 -0.282949 0.0515887 4.141550e-08
311 G  A  0.291274 ⋯ 0.0408391 1.436844e-12 -0.306751 0.05928   2.283848e-07
312 G  A  0.272995 ⋯ 0.0430392 7.090256e-10 -0.333966 0.0700982 1.895512e-06
313 A  T  0.45283  ⋯ 0.0308808 3.379174e-09 0.40971   0.0958919 1.931807e-05
314 A  G  0.439269 ⋯ 0.0435829 9.197327e-14 0.205372  0.0480916 1.950997e-05
315 A  C  0.442217 ⋯ 0.0456758 2.038927e-12 0.223237  0.0499839 7.962523e-06
316 A  G  0.442807 ⋯ 0.0353987 1.010188e-69 0.114917  0.020735  2.987512e-08
317 T  C  0.442217 ⋯ 0.0368867 6.924336e-80 0.102417  0.0185678 3.471534e-08
318 T  C  0.442217 ⋯ 0.0398469 3.687491e-63 0.106964  0.0196156 4.952824e-08
319 T  C  0.452241 ⋯ 0.0371771 8.819912e-22 0.210365  0.0404109 1.933238e-07
320 A  G  0.448113 ⋯ 0.034612  5.723006e-14 0.269528  0.0596629 6.256855e-06
321 C  A  0.457547 ⋯ 0.035382  1.481288e-24 0.191215  0.0380655 5.079098e-07
322 A  G  0.439269 ⋯ 0.0334786 2.504165e-48 0.136387  0.0277887 9.200456e-07
323 A  G  0.439269 ⋯ 0.0319643 2.142767e-22 0.214355  0.0466584 4.345231e-06
324 A  G  0.442807 ⋯ 0.0397941 1.375702e-24 0.176279  0.034764  3.963193e-07
325 A  G  0.448113 ⋯ 0.0315024 3.727312e-17 0.264242  0.0562974 2.683296e-06
326 C  A  0.457547 ⋯ 0.042134  1.749650e-10 0.257352  0.0601478 1.880285e-05
327 A  G  0.439269 ⋯ 0.0411372 1.943943e-38 0.125065  0.0258665 1.331479e-06
328 T  C  0.341392 ⋯ 0.0452016 2.935183e-39 0.131469  0.0295975 8.916590e-06
329 T  C  0.442217 ⋯ 0.0402016 1.679526e-10 0.278414  0.0650451 1.866273e-05
330 A  G  0.448113 ⋯ 0.0274601 8.957901e-12 0.374182  0.0859602 1.343074e-05
331 A  C  0.442217 ⋯ 0.0463325 2.951209e-14 0.203608  0.0442444 4.186797e-06
332 T  C  0.442217 ⋯ 0.0447224 2.608157e-12 0.228479  0.0513444 8.589885e-06
333 C  A  0.457547 ⋯ 0.0411546 5.008168e-12 0.243502  0.0550134 9.589708e-06
334 T  C  0.412146 ⋯ 0.0316018 1.068509e-35 0.165432  0.0322837 2.986215e-07
335 T  C  0.201061 ⋯ 0.0537978 3.045412e-32 0.124226  0.0275568 6.543973e-06
336 G  A  0.271226 ⋯ 0.0378154 2.250754e-15 0.311259  0.0600037 2.133367e-07
337 G  A  0.330778 ⋯ 0.0367777 1.358038e-09 -0.457183 0.100796  5.740608e-06
338 T  C  0.181604 ⋯ 0.057935  1.004490e-61 0.127961  0.0250613 3.291824e-07
    p_HEIDI    nsnp_HEIDI
1   0.07737781 15
2   0.10311220 17
3   0.12394730 16
4   0.30122060 11
5   0.03521279 13
6   0.04550725 8
7   0.01282709 16
8   0.22332970 9
9   0.07710242 20
10  0.08319372 20
11  0.01243084 20
12  0.05276099 7
13  0.13633110 9
14  0.03377731 20
15  0.97549740 3
16  0.05797436 20
17  0.01257932 20
18  0.01277210 20
19  0.12482910 4
20  0.01433074 20
21  0.02924265 7
22  0.03008534 20
23  0.05562339 4
24  0.07857429 20
25  0.01899511 3
26  0.01199084 3
27  0.04614692 3
28  0.03929436 4
29  0.06754042 4
30  0.02143384 11
⋮   ⋮          ⋮
309 0.02685218 13
310 0.04037756 11
311 0.04375718 10
312 0.03251082 9
313 0.12300330 10
314 0.14415930 20
315 0.05151430 18
316 0.03154300 20
317 0.04029319 20
318 0.05545170 20
319 0.02521021 20
320 0.14376140 16
321 0.15368750 20
322 0.02006271 20
323 0.01922315 20
324 0.02125509 20
325 0.02139796 20
326 0.22125850 18
327 0.22483880 20
328 0.03525188 20
329 0.02138115 10
330 0.03787699 14
331 0.06592960 20
332 0.05478502 12
333 0.08704507 19
334 0.07350158 20
335 0.01268503 7
336 0.01960471 10
337 0.04392663 9
338 0.03069465 14
    disease
1   adenosine_deaminase_measurement
2   adenosine_deaminase_measurement
3   adenosine_deaminase_measurement
4   adenosine_deaminase_measurement
5   beta_nerve_growth_factor_measurement
6   beta_nerve_growth_factor_measurement
7   beta_nerve_growth_factor_measurement
8   C_C_motif_chemokine_19_measurement
9   C_C_motif_chemokine_19_measurement
10  C_C_motif_chemokine_19_measurement
11  C_C_motif_chemokine_19_measurement
12  C_C_motif_chemokine_19_measurement
13  C_C_motif_chemokine_19_measurement
14  C_C_motif_chemokine_4_like_measurement
15  C_C_motif_chemokine_4_like_measurement
16  C_C_motif_chemokine_4_like_measurement
17  C_C_motif_chemokine_4_like_measurement
18  C_C_motif_chemokine_4_like_measurement
19  C_C_motif_chemokine_4_like_measurement
20  C_C_motif_chemokine_4_like_measurement
21  C_C_motif_chemokine_4_like_measurement
22  C_C_motif_chemokine_4_like_measurement
23  C_C_motif_chemokine_4_like_measurement
24  C_C_motif_chemokine_4_like_measurement
25  C_C_motif_chemokine_4_like_measurement
26  C_C_motif_chemokine_4_like_measurement
27  C_C_motif_chemokine_4_like_measurement
28  C_C_motif_chemokine_4_like_measurement
29  C_C_motif_chemokine_4_like_measurement
30  C_X_C_motif_chemokine_10_measurement
⋮   ⋮
309 TNF_related_activation_induced_cytokine_measurement
310 TNF_related_activation_induced_cytokine_measurement
311 TNF_related_activation_induced_cytokine_measurement
312 TNF_related_activation_induced_cytokine_measurement
313 TNF_related_apoptosis_inducing_ligand_measurement
314 TNF_related_apoptosis_inducing_ligand_measurement
315 TNF_related_apoptosis_inducing_ligand_measurement
316 TNF_related_apoptosis_inducing_ligand_measurement
317 TNF_related_apoptosis_inducing_ligand_measurement
318 TNF_related_apoptosis_inducing_ligand_measurement
319 TNF_related_apoptosis_inducing_ligand_measurement
320 TNF_related_apoptosis_inducing_ligand_measurement
321 TNF_related_apoptosis_inducing_ligand_measurement
322 TNF_related_apoptosis_inducing_ligand_measurement
323 TNF_related_apoptosis_inducing_ligand_measurement
324 TNF_related_apoptosis_inducing_ligand_measurement
325 TNF_related_apoptosis_inducing_ligand_measurement
326 TNF_related_apoptosis_inducing_ligand_measurement
327 TNF_related_apoptosis_inducing_ligand_measurement
328 TNF_related_apoptosis_inducing_ligand_measurement
329 TNF_related_apoptosis_inducing_ligand_measurement
330 TNF_related_apoptosis_inducing_ligand_measurement
331 TNF_related_apoptosis_inducing_ligand_measurement
332 TNF_related_apoptosis_inducing_ligand_measurement
333 TNF_related_apoptosis_inducing_ligand_measurement
334 transforming_growth_factor_alpha_measurement
335 tumor_necrosis_factor_ligand_superfamily_member_12_measurement
336 tumor_necrosis_factor_receptor_superfamily_member_9_measurement
337 tumor_necrosis_factor_receptor_superfamily_member_9_measurement
338 urokinase_type_plasminogen_activator_measurement
    celltype                                     q_SMR
1   pQTLsmr_CD56bright NK cells                  1.435087e-03
2   pQTLsmr_CD8+ Temra                           6.223835e-05
3   pQTLsmr_GZMB+ CD8+ Tem                       8.904902e-05
4   pQTLsmr_IRF1- GBP2- NDNs                     7.284236e-03
5   pQTLsmr_CD27+ Th17                           4.248768e-02
6   pQTLsmr_Non-classical monocytes              5.651189e-03
7   pQTLsmr_Tfh                                  9.119615e-03
8   pQTLsmr_CD27+ Th17                           1.906911e-02
9   pQTLsmr_Core classical monocytes             6.900397e-03
10  pQTLsmr_GZMK+ CD8+ Tem                       2.115473e-03
11  pQTLsmr_HLA-DRhi CD8+ Tem                    1.243907e-02
12  pQTLsmr_Memory CD4+ Treg                     1.999172e-02
13  pQTLsmr_Tfh                                  1.388233e-02
14  pQTLsmr_Adaptive NK cells                    3.443104e-03
15  pQTLsmr_ALPL- MARCKS- NDNs                   2.141268e-02
16  pQTLsmr_CD56bright NK cells                  5.538051e-03
17  pQTLsmr_cDC1                                 1.145732e-02
18  pQTLsmr_Core classical monocytes             2.229882e-02
19  pQTLsmr_FOS- NDNs                            2.118906e-03
20  pQTLsmr_FOS- NDNs                            1.016390e-02
21  pQTLsmr_GBP1+ classical monocytes            3.492522e-03
22  pQTLsmr_GZMB+ CD8+ Tem                       6.694247e-03
23  pQTLsmr_MT-ATP6- MT-CO2- NDNs                9.506736e-04
24  pQTLsmr_Naïve CD4+ T cells                   1.462079e-02
25  pQTLsmr_Naïve CD8+ T cells                   9.824924e-03
26  pQTLsmr_RGS2- NDNs                           3.392968e-02
27  pQTLsmr_RGS2- NDNs                           4.497364e-03
28  pQTLsmr_VIM- FLNA- NDNs                      2.121680e-02
29  pQTLsmr_VIM- FLNA- NDNs                      2.063660e-03
30  pQTLsmr_Core NDNs                            8.020215e-03
⋮   ⋮                                            ⋮
309 pQTLsmr_Naïve CD4+ T cells                   0.0001542931
310 pQTLsmr_Non-classical monocytes              0.0004883440
311 pQTLsmr_Tfh                                  0.0017953075
312 pQTLsmr_VIM- FLNA- NDNs                      0.0089402455
313 pQTLsmr_CD27+ Th17                           0.0328515378
314 pQTLsmr_CD56bright NK cells                  0.0328515378
315 pQTLsmr_CD56bright NK cells                  0.0170641694
316 pQTLsmr_CD56dim NK cells                     0.0003234233
317 pQTLsmr_CD56dim NK cells                     0.0003234233
318 pQTLsmr_CD8+ Temra                           0.0003234233
319 pQTLsmr_Core NDNs                            0.0009114702
320 pQTLsmr_Core NDNs                            0.0142739046
321 pQTLsmr_GZMB+ CD4+ terminal effector T cells 0.0018905205
322 pQTLsmr_GZMB+ CD8+ Tem                       0.0028493552
323 pQTLsmr_GZMB+ Vδ2+ T cells                  0.0102433027
324 pQTLsmr_Naïve B cells                        0.0015571165
325 pQTLsmr_Naïve CD4+ T cells                   0.0072986683
326 pQTLsmr_Naïve CD4+ T cells                   0.0328515378
327 pQTLsmr_Non-classical monocytes              0.0039234803
328 pQTLsmr_Non-classical monocytes              0.0180168618
329 pQTLsmr_Proliferative NK cells               0.0328515378
330 pQTLsmr_Tfh                                  0.0249956675
331 pQTLsmr_Tfh                                  0.0102101542
332 pQTLsmr_Tfh                                  0.0178672134
333 pQTLsmr_vNKT                                 0.0183295605
334 pQTLsmr_Core classical monocytes             0.0211214987
335 pQTLsmr_VIM- FLNA- NDNs                      0.0094448227
336 pQTLsmr_HLA-DRhi CD8+ Tem                    0.0003572272
337 pQTLsmr_RGS2- NDNs                           0.0076174619
338 pQTLsmr_Naïve CD4+ T cells                   0.0033250244

In [24]:
table(sub_smr_all$disease)

                                          adenosine_deaminase_measurement
                                                                        4
                                     beta_nerve_growth_factor_measurement
                                                                        3
                                       C_C_motif_chemokine_19_measurement
                                                                        6
                                   C_C_motif_chemokine_4_like_measurement
                                                                       16
                                     C_X_C_motif_chemokine_10_measurement
                                                                        3
                                      C_X_C_motif_chemokine_6_measurement
                                                                        1
                                                         CCL2_measurement
                                                                        1
                              CUB_domain_containing_protein_1_measurement
                                                                        8
                                                   cystatin_D_measurement
                                                                       10
delta_and_Notch_like_epidermal_growth_factor_related_receptor_measurement
                                                                        2
                                  fibroblast_growth_factor_23_measurement
                                                                        4
                                                  fractalkine_measurement
                                                                       40
                  glial_cell_line_derived_neurotrophic_factor_measurement
                                                                        5
                                          interleukin_1_alpha_measurement
                                                                        3
                                               interleukin_10_measurement
                                                                        3
                         interleukin_10_receptor_subunit_beta_measurement
                                                                       32
                        interleukin_15_receptor_subunit_alpha_measurement
                                                                        2
                                               interleukin_18_measurement
                                                                        9
                                    interleukin_18_receptor_1_measurement
                                                                        2
                            level_of_interleukin_12_subunit_beta_in_blood
                                                                       27
                                            lymphotoxin_alpha_measurement
                                                                       27
                           macrophage_inflammatory_protein_1a_measurement
                                                                        2
                                                 oncostatin_M_measurement
                                                                       51
                                              osteoprotegerin_measurement
                                                                        1
                             programmed_cell_death_1_ligand_1_measurement
                                                                        1
                                             stem_Cell_Factor_measurement
                                                                       24
                                          sulfotrasferase_1A1_measurement
                                                                        2
                              t_cell_surface_glycoprotein_CD5_measurement
                                                                       17
                      TNF_related_activation_induced_cytokine_measurement
                                                                        6
                        TNF_related_apoptosis_inducing_ligand_measurement
                                                                       21
                             transforming_growth_factor_alpha_measurement
                                                                        1
           tumor_necrosis_factor_ligand_superfamily_member_12_measurement
                                                                        1
          tumor_necrosis_factor_receptor_superfamily_member_9_measurement
                                                                        2
                         urokinase_type_plasminogen_activator_measurement
                                                                        1

In [25]:
write.csv(sub_smr_all,'/media/AnalysisDisk2/Yangshichen/2_My-Onek/WGS/Result/SMR_eQTL_pQTL_2.csv')